// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using Nhentai.Api.Api.V2.Moderation.ApiKeys.Item;
using Nhentai.Api.Models;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace Nhentai.Api.Api.V2.Moderation.ApiKeys
{
    /// <summary>
    /// Builds and executes requests for operations under \api\v2\moderation\api-keys
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class ApiKeysRequestBuilder : BaseRequestBuilder
    {
        /// <summary>Gets an item from the Nhentai.Api.api.v2.moderation.apiKeys.item collection</summary>
        /// <param name="position">Unique identifier of the item</param>
        /// <returns>A <see cref="global::Nhentai.Api.Api.V2.Moderation.ApiKeys.Item.WithKey_ItemRequestBuilder"/></returns>
        public global::Nhentai.Api.Api.V2.Moderation.ApiKeys.Item.WithKey_ItemRequestBuilder this[string position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                urlTplParams.Add("key_id", position);
                return new global::Nhentai.Api.Api.V2.Moderation.ApiKeys.Item.WithKey_ItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Nhentai.Api.Api.V2.Moderation.ApiKeys.ApiKeysRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public ApiKeysRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/v2/moderation/api-keys{?page*,per_page*}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Nhentai.Api.Api.V2.Moderation.ApiKeys.ApiKeysRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public ApiKeysRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/v2/moderation/api-keys{?page*,per_page*}", rawUrl)
        {
        }
        /// <summary>
        /// List all active API keys with user info. Admin only.---**Auth:** Superuser Token required
        /// </summary>
        /// <returns>A <see cref="global::Nhentai.Api.Api.V2.Moderation.ApiKeys.ApiKeysGetResponse"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::Nhentai.Api.Models.ErrorResponse">When receiving a 403 status code</exception>
        /// <exception cref="global::Nhentai.Api.Models.HTTPValidationError">When receiving a 422 status code</exception>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::Nhentai.Api.Api.V2.Moderation.ApiKeys.ApiKeysGetResponse?> GetAsApiKeysGetResponseAsync(Action<RequestConfiguration<global::Nhentai.Api.Api.V2.Moderation.ApiKeys.ApiKeysRequestBuilder.ApiKeysRequestBuilderGetQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::Nhentai.Api.Api.V2.Moderation.ApiKeys.ApiKeysGetResponse> GetAsApiKeysGetResponseAsync(Action<RequestConfiguration<global::Nhentai.Api.Api.V2.Moderation.ApiKeys.ApiKeysRequestBuilder.ApiKeysRequestBuilderGetQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToGetRequestInformation(requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "403", global::Nhentai.Api.Models.ErrorResponse.CreateFromDiscriminatorValue },
                { "422", global::Nhentai.Api.Models.HTTPValidationError.CreateFromDiscriminatorValue },
            };
            return await RequestAdapter.SendAsync<global::Nhentai.Api.Api.V2.Moderation.ApiKeys.ApiKeysGetResponse>(requestInfo, global::Nhentai.Api.Api.V2.Moderation.ApiKeys.ApiKeysGetResponse.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// List all active API keys with user info. Admin only.---**Auth:** Superuser Token required
        /// </summary>
        /// <returns>A <see cref="global::Nhentai.Api.Api.V2.Moderation.ApiKeys.ApiKeysResponse"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::Nhentai.Api.Models.ErrorResponse">When receiving a 403 status code</exception>
        /// <exception cref="global::Nhentai.Api.Models.HTTPValidationError">When receiving a 422 status code</exception>
        [Obsolete("This method is obsolete. Use GetAsApiKeysGetResponseAsync instead.")]
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::Nhentai.Api.Api.V2.Moderation.ApiKeys.ApiKeysResponse?> GetAsync(Action<RequestConfiguration<global::Nhentai.Api.Api.V2.Moderation.ApiKeys.ApiKeysRequestBuilder.ApiKeysRequestBuilderGetQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::Nhentai.Api.Api.V2.Moderation.ApiKeys.ApiKeysResponse> GetAsync(Action<RequestConfiguration<global::Nhentai.Api.Api.V2.Moderation.ApiKeys.ApiKeysRequestBuilder.ApiKeysRequestBuilderGetQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToGetRequestInformation(requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "403", global::Nhentai.Api.Models.ErrorResponse.CreateFromDiscriminatorValue },
                { "422", global::Nhentai.Api.Models.HTTPValidationError.CreateFromDiscriminatorValue },
            };
            return await RequestAdapter.SendAsync<global::Nhentai.Api.Api.V2.Moderation.ApiKeys.ApiKeysResponse>(requestInfo, global::Nhentai.Api.Api.V2.Moderation.ApiKeys.ApiKeysResponse.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// List all active API keys with user info. Admin only.---**Auth:** Superuser Token required
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::Nhentai.Api.Api.V2.Moderation.ApiKeys.ApiKeysRequestBuilder.ApiKeysRequestBuilderGetQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::Nhentai.Api.Api.V2.Moderation.ApiKeys.ApiKeysRequestBuilder.ApiKeysRequestBuilderGetQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.GET, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::Nhentai.Api.Api.V2.Moderation.ApiKeys.ApiKeysRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::Nhentai.Api.Api.V2.Moderation.ApiKeys.ApiKeysRequestBuilder WithUrl(string rawUrl)
        {
            return new global::Nhentai.Api.Api.V2.Moderation.ApiKeys.ApiKeysRequestBuilder(rawUrl, RequestAdapter);
        }
        /// <summary>
        /// List all active API keys with user info. Admin only.---**Auth:** Superuser Token required
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class ApiKeysRequestBuilderGetQueryParameters 
        {
            [QueryParameter("page")]
            public int? Page { get; set; }
            [QueryParameter("per_page")]
            public int? PerPage { get; set; }
        }
        /// <summary>
        /// Configuration for the request such as headers, query parameters, and middleware options.
        /// </summary>
        [Obsolete("This class is deprecated. Please use the generic RequestConfiguration class generated by the generator.")]
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class ApiKeysRequestBuilderGetRequestConfiguration : RequestConfiguration<global::Nhentai.Api.Api.V2.Moderation.ApiKeys.ApiKeysRequestBuilder.ApiKeysRequestBuilderGetQueryParameters>
        {
        }
    }
}
#pragma warning restore CS0618
