// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using Nhentai.Api.Api.V2.Auth.Login;
using Nhentai.Api.Api.V2.Auth.Logout;
using Nhentai.Api.Api.V2.Auth.Refresh;
using Nhentai.Api.Api.V2.Auth.Register;
using Nhentai.Api.Api.V2.Auth.Reset;
using Nhentai.Api.Api.V2.Auth.Sessions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace Nhentai.Api.Api.V2.Auth
{
    /// <summary>
    /// Builds and executes requests for operations under \api\v2\auth
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class AuthRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The login property</summary>
        public global::Nhentai.Api.Api.V2.Auth.Login.LoginRequestBuilder Login
        {
            get => new global::Nhentai.Api.Api.V2.Auth.Login.LoginRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The logout property</summary>
        public global::Nhentai.Api.Api.V2.Auth.Logout.LogoutRequestBuilder Logout
        {
            get => new global::Nhentai.Api.Api.V2.Auth.Logout.LogoutRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The refresh property</summary>
        public global::Nhentai.Api.Api.V2.Auth.Refresh.RefreshRequestBuilder Refresh
        {
            get => new global::Nhentai.Api.Api.V2.Auth.Refresh.RefreshRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The register property</summary>
        public global::Nhentai.Api.Api.V2.Auth.Register.RegisterRequestBuilder Register
        {
            get => new global::Nhentai.Api.Api.V2.Auth.Register.RegisterRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The reset property</summary>
        public global::Nhentai.Api.Api.V2.Auth.Reset.ResetRequestBuilder Reset
        {
            get => new global::Nhentai.Api.Api.V2.Auth.Reset.ResetRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The sessions property</summary>
        public global::Nhentai.Api.Api.V2.Auth.Sessions.SessionsRequestBuilder Sessions
        {
            get => new global::Nhentai.Api.Api.V2.Auth.Sessions.SessionsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Nhentai.Api.Api.V2.Auth.AuthRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public AuthRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/v2/auth", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Nhentai.Api.Api.V2.Auth.AuthRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public AuthRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/v2/auth", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
