// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Nhentai.Api.Api.V2.Galleries.Tagged
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum GetSortQueryParameterType
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "date")]
        #pragma warning disable CS1591
        Date,
        #pragma warning restore CS1591
        [EnumMember(Value = "popular")]
        #pragma warning disable CS1591
        Popular,
        #pragma warning restore CS1591
        [EnumMember(Value = "popular-today")]
        #pragma warning disable CS1591
        PopularToday,
        #pragma warning restore CS1591
        [EnumMember(Value = "popular-week")]
        #pragma warning disable CS1591
        PopularWeek,
        #pragma warning restore CS1591
        [EnumMember(Value = "popular-month")]
        #pragma warning disable CS1591
        PopularMonth,
        #pragma warning restore CS1591
    }
}
