// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using Nhentai.Api.Models;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace Nhentai.Api.Api.V2.Galleries.Tagged
{
    /// <summary>
    /// Builds and executes requests for operations under \api\v2\galleries\tagged
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class TaggedRequestBuilder : BaseRequestBuilder
    {
        /// <summary>
        /// Instantiates a new <see cref="global::Nhentai.Api.Api.V2.Galleries.Tagged.TaggedRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public TaggedRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/v2/galleries/tagged?tag_id={tag_id}{&page*,per_page*,sort*}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Nhentai.Api.Api.V2.Galleries.Tagged.TaggedRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public TaggedRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/v2/galleries/tagged?tag_id={tag_id}{&page*,per_page*,sort*}", rawUrl)
        {
        }
        /// <summary>
        /// Get galleries with a specific tag.---**Auth:** Public (optional User Token or API Key for personalization)**Rate limits:**- 30/1min per IP
        /// </summary>
        /// <returns>A <see cref="global::Nhentai.Api.Models.PaginatedResponse_GalleryListItem_"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::Nhentai.Api.Models.ErrorResponse">When receiving a 404 status code</exception>
        /// <exception cref="global::Nhentai.Api.Models.HTTPValidationError">When receiving a 422 status code</exception>
        /// <exception cref="global::Nhentai.Api.Models.ErrorResponse">When receiving a 429 status code</exception>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::Nhentai.Api.Models.PaginatedResponse_GalleryListItem_?> GetAsync(Action<RequestConfiguration<global::Nhentai.Api.Api.V2.Galleries.Tagged.TaggedRequestBuilder.TaggedRequestBuilderGetQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::Nhentai.Api.Models.PaginatedResponse_GalleryListItem_> GetAsync(Action<RequestConfiguration<global::Nhentai.Api.Api.V2.Galleries.Tagged.TaggedRequestBuilder.TaggedRequestBuilderGetQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToGetRequestInformation(requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "404", global::Nhentai.Api.Models.ErrorResponse.CreateFromDiscriminatorValue },
                { "422", global::Nhentai.Api.Models.HTTPValidationError.CreateFromDiscriminatorValue },
                { "429", global::Nhentai.Api.Models.ErrorResponse.CreateFromDiscriminatorValue },
            };
            return await RequestAdapter.SendAsync<global::Nhentai.Api.Models.PaginatedResponse_GalleryListItem_>(requestInfo, global::Nhentai.Api.Models.PaginatedResponse_GalleryListItem_.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Get galleries with a specific tag.---**Auth:** Public (optional User Token or API Key for personalization)**Rate limits:**- 30/1min per IP
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::Nhentai.Api.Api.V2.Galleries.Tagged.TaggedRequestBuilder.TaggedRequestBuilderGetQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::Nhentai.Api.Api.V2.Galleries.Tagged.TaggedRequestBuilder.TaggedRequestBuilderGetQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.GET, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::Nhentai.Api.Api.V2.Galleries.Tagged.TaggedRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::Nhentai.Api.Api.V2.Galleries.Tagged.TaggedRequestBuilder WithUrl(string rawUrl)
        {
            return new global::Nhentai.Api.Api.V2.Galleries.Tagged.TaggedRequestBuilder(rawUrl, RequestAdapter);
        }
        /// <summary>
        /// Get galleries with a specific tag.---**Auth:** Public (optional User Token or API Key for personalization)**Rate limits:**- 30/1min per IP
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class TaggedRequestBuilderGetQueryParameters 
        {
            /// <summary>Page number</summary>
            [QueryParameter("page")]
            public int? Page { get; set; }
            /// <summary>Items per page</summary>
            [QueryParameter("per_page")]
            public int? PerPage { get; set; }
            [Obsolete("This property is deprecated, use SortAsGetSortQueryParameterType instead")]
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("sort")]
            public string? Sort { get; set; }
#nullable restore
#else
            [QueryParameter("sort")]
            public string Sort { get; set; }
#endif
            [QueryParameter("sort")]
            public global::Nhentai.Api.Api.V2.Galleries.Tagged.GetSortQueryParameterType? SortAsGetSortQueryParameterType { get; set; }
            /// <summary>Tag ID to filter by</summary>
            [QueryParameter("tag_id")]
            public int? TagId { get; set; }
        }
        /// <summary>
        /// Configuration for the request such as headers, query parameters, and middleware options.
        /// </summary>
        [Obsolete("This class is deprecated. Please use the generic RequestConfiguration class generated by the generator.")]
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class TaggedRequestBuilderGetRequestConfiguration : RequestConfiguration<global::Nhentai.Api.Api.V2.Galleries.Tagged.TaggedRequestBuilder.TaggedRequestBuilderGetQueryParameters>
        {
        }
    }
}
#pragma warning restore CS0618
