// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using Nh.Api.Models;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace Nh.Api.Api.V2.Tags.Ids
{
    /// <summary>
    /// Builds and executes requests for operations under \api\v2\tags\ids
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class IdsRequestBuilder : BaseRequestBuilder
    {
        /// <summary>
        /// Instantiates a new <see cref="global::Nh.Api.Api.V2.Tags.Ids.IdsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public IdsRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/v2/tags/ids?ids={ids}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Nh.Api.Api.V2.Tags.Ids.IdsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public IdsRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/v2/tags/ids?ids={ids}", rawUrl)
        {
        }
        /// <summary>
        /// Look up multiple tags by ID. Max 100 per request.---**Auth:** Public (no authentication required)**Rate limits:**- 15/1min per IP
        /// </summary>
        /// <returns>A List&lt;global::Nhentai.Api.Models.TagResponse&gt;</returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::Nh.Api.Models.HTTPValidationError">When receiving a 422 status code</exception>
        /// <exception cref="global::Nh.Api.Models.ErrorResponse">When receiving a 429 status code</exception>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<List<global::Nh.Api.Models.TagResponse>?> GetAsync(Action<RequestConfiguration<global::Nh.Api.Api.V2.Tags.Ids.IdsRequestBuilder.IdsRequestBuilderGetQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<List<global::Nhentai.Api.Models.TagResponse>> GetAsync(Action<RequestConfiguration<global::Nhentai.Api.Api.V2.Tags.Ids.IdsRequestBuilder.IdsRequestBuilderGetQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToGetRequestInformation(requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "422", global::Nh.Api.Models.HTTPValidationError.CreateFromDiscriminatorValue },
                { "429", global::Nh.Api.Models.ErrorResponse.CreateFromDiscriminatorValue },
            };
            var collectionResult = await RequestAdapter.SendCollectionAsync<global::Nh.Api.Models.TagResponse>(requestInfo, global::Nh.Api.Models.TagResponse.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
            return collectionResult?.AsList();
        }
        /// <summary>
        /// Look up multiple tags by ID. Max 100 per request.---**Auth:** Public (no authentication required)**Rate limits:**- 15/1min per IP
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::Nh.Api.Api.V2.Tags.Ids.IdsRequestBuilder.IdsRequestBuilderGetQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::Nhentai.Api.Api.V2.Tags.Ids.IdsRequestBuilder.IdsRequestBuilderGetQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.GET, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::Nh.Api.Api.V2.Tags.Ids.IdsRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::Nh.Api.Api.V2.Tags.Ids.IdsRequestBuilder WithUrl(string rawUrl)
        {
            return new global::Nh.Api.Api.V2.Tags.Ids.IdsRequestBuilder(rawUrl, RequestAdapter);
        }
        /// <summary>
        /// Look up multiple tags by ID. Max 100 per request.---**Auth:** Public (no authentication required)**Rate limits:**- 15/1min per IP
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class IdsRequestBuilderGetQueryParameters 
        {
            /// <summary>Comma-separated tag IDs</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("ids")]
            public string? Ids { get; set; }
#nullable restore
#else
            [QueryParameter("ids")]
            public string Ids { get; set; }
#endif
        }
        /// <summary>
        /// Configuration for the request such as headers, query parameters, and middleware options.
        /// </summary>
        [Obsolete("This class is deprecated. Please use the generic RequestConfiguration class generated by the generator.")]
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class IdsRequestBuilderGetRequestConfiguration : RequestConfiguration<global::Nh.Api.Api.V2.Tags.Ids.IdsRequestBuilder.IdsRequestBuilderGetQueryParameters>
        {
        }
    }
}
#pragma warning restore CS0618
