// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using Nh.Api.Models;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace Nh.Api.Api.V2.Moderation.Edits.Item.Reject
{
    /// <summary>
    /// Builds and executes requests for operations under \api\v2\moderation\edits\{edit_id}\reject
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class RejectRequestBuilder : BaseRequestBuilder
    {
        /// <summary>
        /// Instantiates a new <see cref="global::Nh.Api.Api.V2.Moderation.Edits.Item.Reject.RejectRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public RejectRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/v2/moderation/edits/{edit_id}/reject", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Nh.Api.Api.V2.Moderation.Edits.Item.Reject.RejectRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public RejectRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/v2/moderation/edits/{edit_id}/reject", rawUrl)
        {
        }
        /// <summary>
        /// Reject a pending edit.Staff only. Use this to force-reject an edit regardless of votes.---**Auth:** Staff Token required**Rate limits:**- 30/15min per user
        /// </summary>
        /// <returns>A <see cref="global::Nh.Api.Models.SuccessResponse"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::Nh.Api.Models.ErrorResponse">When receiving a 400 status code</exception>
        /// <exception cref="global::Nh.Api.Models.ErrorResponse">When receiving a 403 status code</exception>
        /// <exception cref="global::Nh.Api.Models.ErrorResponse">When receiving a 404 status code</exception>
        /// <exception cref="global::Nh.Api.Models.HTTPValidationError">When receiving a 422 status code</exception>
        /// <exception cref="global::Nh.Api.Models.ErrorResponse">When receiving a 429 status code</exception>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::Nh.Api.Models.SuccessResponse?> PostAsync(Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::Nhentai.Api.Models.SuccessResponse> PostAsync(Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToPostRequestInformation(requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "400", global::Nh.Api.Models.ErrorResponse.CreateFromDiscriminatorValue },
                { "403", global::Nh.Api.Models.ErrorResponse.CreateFromDiscriminatorValue },
                { "404", global::Nh.Api.Models.ErrorResponse.CreateFromDiscriminatorValue },
                { "422", global::Nh.Api.Models.HTTPValidationError.CreateFromDiscriminatorValue },
                { "429", global::Nh.Api.Models.ErrorResponse.CreateFromDiscriminatorValue },
            };
            return await RequestAdapter.SendAsync<global::Nh.Api.Models.SuccessResponse>(requestInfo, global::Nh.Api.Models.SuccessResponse.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Reject a pending edit.Staff only. Use this to force-reject an edit regardless of votes.---**Auth:** Staff Token required**Rate limits:**- 30/15min per user
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToPostRequestInformation(Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToPostRequestInformation(Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.POST, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::Nh.Api.Api.V2.Moderation.Edits.Item.Reject.RejectRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::Nh.Api.Api.V2.Moderation.Edits.Item.Reject.RejectRequestBuilder WithUrl(string rawUrl)
        {
            return new global::Nh.Api.Api.V2.Moderation.Edits.Item.Reject.RejectRequestBuilder(rawUrl, RequestAdapter);
        }
        /// <summary>
        /// Configuration for the request such as headers, query parameters, and middleware options.
        /// </summary>
        [Obsolete("This class is deprecated. Please use the generic RequestConfiguration class generated by the generator.")]
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class RejectRequestBuilderPostRequestConfiguration : RequestConfiguration<DefaultQueryParameters>
        {
        }
    }
}
#pragma warning restore CS0618
