// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using Nh.Api.Api.V2.Moderation.Bulk.Hide;
using Nh.Api.Api.V2.Moderation.Bulk.Shadowban;
using Nh.Api.Api.V2.Moderation.Bulk.Unhide;
using Nh.Api.Api.V2.Moderation.Bulk.Unshadowban;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace Nh.Api.Api.V2.Moderation.Bulk
{
    /// <summary>
    /// Builds and executes requests for operations under \api\v2\moderation\bulk
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class BulkRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The hide property</summary>
        public global::Nh.Api.Api.V2.Moderation.Bulk.Hide.HideRequestBuilder Hide
        {
            get => new global::Nh.Api.Api.V2.Moderation.Bulk.Hide.HideRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The shadowban property</summary>
        public global::Nh.Api.Api.V2.Moderation.Bulk.Shadowban.ShadowbanRequestBuilder Shadowban
        {
            get => new global::Nh.Api.Api.V2.Moderation.Bulk.Shadowban.ShadowbanRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The unhide property</summary>
        public global::Nh.Api.Api.V2.Moderation.Bulk.Unhide.UnhideRequestBuilder Unhide
        {
            get => new global::Nh.Api.Api.V2.Moderation.Bulk.Unhide.UnhideRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The unshadowban property</summary>
        public global::Nh.Api.Api.V2.Moderation.Bulk.Unshadowban.UnshadowbanRequestBuilder Unshadowban
        {
            get => new global::Nh.Api.Api.V2.Moderation.Bulk.Unshadowban.UnshadowbanRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Nh.Api.Api.V2.Moderation.Bulk.BulkRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public BulkRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/v2/moderation/bulk", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Nh.Api.Api.V2.Moderation.Bulk.BulkRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public BulkRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/v2/moderation/bulk", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
