// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using Nhentai.Api.Api.V2.Moderation.ApiKeys;
using Nhentai.Api.Api.V2.Moderation.Bulk;
using Nhentai.Api.Api.V2.Moderation.Comments;
using Nhentai.Api.Api.V2.Moderation.Edits;
using Nhentai.Api.Api.V2.Moderation.Flags;
using Nhentai.Api.Api.V2.Moderation.Users;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace Nhentai.Api.Api.V2.Moderation
{
    /// <summary>
    /// Builds and executes requests for operations under \api\v2\moderation
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class ModerationRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The apiKeys property</summary>
        public global::Nhentai.Api.Api.V2.Moderation.ApiKeys.ApiKeysRequestBuilder ApiKeys
        {
            get => new global::Nhentai.Api.Api.V2.Moderation.ApiKeys.ApiKeysRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The bulk property</summary>
        public global::Nhentai.Api.Api.V2.Moderation.Bulk.BulkRequestBuilder Bulk
        {
            get => new global::Nhentai.Api.Api.V2.Moderation.Bulk.BulkRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The comments property</summary>
        public global::Nhentai.Api.Api.V2.Moderation.Comments.CommentsRequestBuilder Comments
        {
            get => new global::Nhentai.Api.Api.V2.Moderation.Comments.CommentsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The edits property</summary>
        public global::Nhentai.Api.Api.V2.Moderation.Edits.EditsRequestBuilder Edits
        {
            get => new global::Nhentai.Api.Api.V2.Moderation.Edits.EditsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The flags property</summary>
        public global::Nhentai.Api.Api.V2.Moderation.Flags.FlagsRequestBuilder Flags
        {
            get => new global::Nhentai.Api.Api.V2.Moderation.Flags.FlagsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The users property</summary>
        public global::Nhentai.Api.Api.V2.Moderation.Users.UsersRequestBuilder Users
        {
            get => new global::Nhentai.Api.Api.V2.Moderation.Users.UsersRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Nhentai.Api.Api.V2.Moderation.ModerationRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public ModerationRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/v2/moderation", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Nhentai.Api.Api.V2.Moderation.ModerationRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public ModerationRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/v2/moderation", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
