// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using Nhentai.Api.Api.V2.Moderation.Comments.Item;
using Nhentai.Api.Api.V2.Moderation.Comments.Recent;
using Nhentai.Api.Api.V2.Moderation.Comments.Spam;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace Nhentai.Api.Api.V2.Moderation.Comments
{
    /// <summary>
    /// Builds and executes requests for operations under \api\v2\moderation\comments
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class CommentsRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The recent property</summary>
        public global::Nhentai.Api.Api.V2.Moderation.Comments.Recent.RecentRequestBuilder Recent
        {
            get => new global::Nhentai.Api.Api.V2.Moderation.Comments.Recent.RecentRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The spam property</summary>
        public global::Nhentai.Api.Api.V2.Moderation.Comments.Spam.SpamRequestBuilder Spam
        {
            get => new global::Nhentai.Api.Api.V2.Moderation.Comments.Spam.SpamRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>Gets an item from the Nhentai.Api.api.v2.moderation.comments.item collection</summary>
        /// <param name="position">Unique identifier of the item</param>
        /// <returns>A <see cref="global::Nhentai.Api.Api.V2.Moderation.Comments.Item.WithComment_ItemRequestBuilder"/></returns>
        public global::Nhentai.Api.Api.V2.Moderation.Comments.Item.WithComment_ItemRequestBuilder this[int position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                urlTplParams.Add("comment_id", position);
                return new global::Nhentai.Api.Api.V2.Moderation.Comments.Item.WithComment_ItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>Gets an item from the Nhentai.Api.api.v2.moderation.comments.item collection</summary>
        /// <param name="position">Unique identifier of the item</param>
        /// <returns>A <see cref="global::Nhentai.Api.Api.V2.Moderation.Comments.Item.WithComment_ItemRequestBuilder"/></returns>
        [Obsolete("This indexer is deprecated and will be removed in the next major version. Use the one with the typed parameter instead.")]
        public global::Nhentai.Api.Api.V2.Moderation.Comments.Item.WithComment_ItemRequestBuilder this[string position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                if (!string.IsNullOrWhiteSpace(position)) urlTplParams.Add("comment_id", position);
                return new global::Nhentai.Api.Api.V2.Moderation.Comments.Item.WithComment_ItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Nhentai.Api.Api.V2.Moderation.Comments.CommentsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public CommentsRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/v2/moderation/comments", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Nhentai.Api.Api.V2.Moderation.Comments.CommentsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public CommentsRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/v2/moderation/comments", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
