// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using Nhentai.Api.Models;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace Nhentai.Api.Api.V2.Auth.Register
{
    /// <summary>
    /// Builds and executes requests for operations under \api\v2\auth\register
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class RegisterRequestBuilder : BaseRequestBuilder
    {
        /// <summary>
        /// Instantiates a new <see cref="global::Nhentai.Api.Api.V2.Auth.Register.RegisterRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public RegisterRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/v2/auth/register", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Nhentai.Api.Api.V2.Auth.Register.RegisterRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public RegisterRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/v2/auth/register", rawUrl)
        {
        }
        /// <summary>
        /// Create a new account.Returns access token and refresh token.---**Auth:** Public (no authentication required)**Feature Flag:** `allow_register` must be enabled**Protection:** Proof of Work required (`GET /api/v2/pow?action=register`)**Protection:** CAPTCHA required (`GET /api/v2/captcha` for provider info)**Rate limits:**- 3/1h per IP
        /// </summary>
        /// <returns>A <see cref="global::Nhentai.Api.Models.TokenResponse"/></returns>
        /// <param name="body">The request body</param>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::Nhentai.Api.Models.ErrorResponse">When receiving a 400 status code</exception>
        /// <exception cref="global::Nhentai.Api.Models.ErrorResponse">When receiving a 409 status code</exception>
        /// <exception cref="global::Nhentai.Api.Models.HTTPValidationError">When receiving a 422 status code</exception>
        /// <exception cref="global::Nhentai.Api.Models.ErrorResponse">When receiving a 429 status code</exception>
        /// <exception cref="global::Nhentai.Api.Models.ErrorResponse">When receiving a 503 status code</exception>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::Nhentai.Api.Models.TokenResponse?> PostAsync(global::Nhentai.Api.Models.Body_register_api_v2_auth_register_post body, Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::Nhentai.Api.Models.TokenResponse> PostAsync(global::Nhentai.Api.Models.Body_register_api_v2_auth_register_post body, Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = ToPostRequestInformation(body, requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "400", global::Nhentai.Api.Models.ErrorResponse.CreateFromDiscriminatorValue },
                { "409", global::Nhentai.Api.Models.ErrorResponse.CreateFromDiscriminatorValue },
                { "422", global::Nhentai.Api.Models.HTTPValidationError.CreateFromDiscriminatorValue },
                { "429", global::Nhentai.Api.Models.ErrorResponse.CreateFromDiscriminatorValue },
                { "503", global::Nhentai.Api.Models.ErrorResponse.CreateFromDiscriminatorValue },
            };
            return await RequestAdapter.SendAsync<global::Nhentai.Api.Models.TokenResponse>(requestInfo, global::Nhentai.Api.Models.TokenResponse.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Create a new account.Returns access token and refresh token.---**Auth:** Public (no authentication required)**Feature Flag:** `allow_register` must be enabled**Protection:** Proof of Work required (`GET /api/v2/pow?action=register`)**Protection:** CAPTCHA required (`GET /api/v2/captcha` for provider info)**Rate limits:**- 3/1h per IP
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="body">The request body</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToPostRequestInformation(global::Nhentai.Api.Models.Body_register_api_v2_auth_register_post body, Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToPostRequestInformation(global::Nhentai.Api.Models.Body_register_api_v2_auth_register_post body, Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = new RequestInformation(Method.POST, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            requestInfo.SetContentFromParsable(RequestAdapter, "application/json", body);
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::Nhentai.Api.Api.V2.Auth.Register.RegisterRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::Nhentai.Api.Api.V2.Auth.Register.RegisterRequestBuilder WithUrl(string rawUrl)
        {
            return new global::Nhentai.Api.Api.V2.Auth.Register.RegisterRequestBuilder(rawUrl, RequestAdapter);
        }
        /// <summary>
        /// Configuration for the request such as headers, query parameters, and middleware options.
        /// </summary>
        [Obsolete("This class is deprecated. Please use the generic RequestConfiguration class generated by the generator.")]
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class RegisterRequestBuilderPostRequestConfiguration : RequestConfiguration<DefaultQueryParameters>
        {
        }
    }
}
#pragma warning restore CS0618
