// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using Nhentai.Api.Api.V2.Zones.H;
using Nhentai.Api.Api.V2.Zones.I;
using Nhentai.Api.Api.V2.Zones.Pu;
using Nhentai.Api.Models;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace Nhentai.Api.Api.V2.Zones
{
    /// <summary>
    /// Builds and executes requests for operations under \api\v2\zones
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class ZonesRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The h property</summary>
        public global::Nhentai.Api.Api.V2.Zones.H.HRequestBuilder H
        {
            get => new global::Nhentai.Api.Api.V2.Zones.H.HRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The i property</summary>
        public global::Nhentai.Api.Api.V2.Zones.I.IRequestBuilder I
        {
            get => new global::Nhentai.Api.Api.V2.Zones.I.IRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The pu property</summary>
        public global::Nhentai.Api.Api.V2.Zones.Pu.PuRequestBuilder Pu
        {
            get => new global::Nhentai.Api.Api.V2.Zones.Pu.PuRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Nhentai.Api.Api.V2.Zones.ZonesRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public ZonesRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/v2/zones", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Nhentai.Api.Api.V2.Zones.ZonesRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public ZonesRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/v2/zones", rawUrl)
        {
        }
        /// <summary>
        /// Get ad HTML for all zones.Returns:    Dict mapping zone spec to HTML for all active zones.---**Auth:** Public (no authentication required)
        /// </summary>
        /// <returns>A <see cref="global::Nhentai.Api.Api.V2.Zones.ZonesResponse"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::Nhentai.Api.Models.HTTPValidationError">When receiving a 422 status code</exception>
        [Obsolete("This method is obsolete. Use GetAsZonesGetResponseAsync instead.")]
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::Nhentai.Api.Api.V2.Zones.ZonesResponse?> GetAsync(Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::Nhentai.Api.Api.V2.Zones.ZonesResponse> GetAsync(Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToGetRequestInformation(requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "422", global::Nhentai.Api.Models.HTTPValidationError.CreateFromDiscriminatorValue },
            };
            return await RequestAdapter.SendAsync<global::Nhentai.Api.Api.V2.Zones.ZonesResponse>(requestInfo, global::Nhentai.Api.Api.V2.Zones.ZonesResponse.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Get ad HTML for all zones.Returns:    Dict mapping zone spec to HTML for all active zones.---**Auth:** Public (no authentication required)
        /// </summary>
        /// <returns>A <see cref="global::Nhentai.Api.Api.V2.Zones.ZonesGetResponse"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::Nhentai.Api.Models.HTTPValidationError">When receiving a 422 status code</exception>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::Nhentai.Api.Api.V2.Zones.ZonesGetResponse?> GetAsZonesGetResponseAsync(Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::Nhentai.Api.Api.V2.Zones.ZonesGetResponse> GetAsZonesGetResponseAsync(Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToGetRequestInformation(requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "422", global::Nhentai.Api.Models.HTTPValidationError.CreateFromDiscriminatorValue },
            };
            return await RequestAdapter.SendAsync<global::Nhentai.Api.Api.V2.Zones.ZonesGetResponse>(requestInfo, global::Nhentai.Api.Api.V2.Zones.ZonesGetResponse.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Get ad HTML for all zones.Returns:    Dict mapping zone spec to HTML for all active zones.---**Auth:** Public (no authentication required)
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.GET, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::Nhentai.Api.Api.V2.Zones.ZonesRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::Nhentai.Api.Api.V2.Zones.ZonesRequestBuilder WithUrl(string rawUrl)
        {
            return new global::Nhentai.Api.Api.V2.Zones.ZonesRequestBuilder(rawUrl, RequestAdapter);
        }
        /// <summary>
        /// Configuration for the request such as headers, query parameters, and middleware options.
        /// </summary>
        [Obsolete("This class is deprecated. Please use the generic RequestConfiguration class generated by the generator.")]
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class ZonesRequestBuilderGetRequestConfiguration : RequestConfiguration<DefaultQueryParameters>
        {
        }
    }
}
#pragma warning restore CS0618
