// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Nh.Api.Models
{
    /// <summary>
    /// Single edit response.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class EditResponse : IAdditionalDataHolder, IParsable
    {
        /// <summary>The accepted property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Nh.Api.Models.EditResponse.EditResponse_accepted? Accepted { get; set; }
#nullable restore
#else
        public global::Nhentai.Api.Models.EditResponse.EditResponse_accepted Accepted { get; set; }
#endif
        /// <summary>The added_tags property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Nh.Api.Models.EditTagInfo>? AddedTags { get; set; }
#nullable restore
#else
        public List<global::Nhentai.Api.Models.EditTagInfo> AddedTags { get; set; }
#endif
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The created_tags property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Nh.Api.Models.CreatedTag>? CreatedTags { get; set; }
#nullable restore
#else
        public List<global::Nhentai.Api.Models.CreatedTag> CreatedTags { get; set; }
#endif
        /// <summary>The date property</summary>
        public int? Date { get; set; }
        /// <summary>The downvotes property</summary>
        public int? Downvotes { get; set; }
        /// <summary>The gallery_id property</summary>
        public int? GalleryId { get; set; }
        /// <summary>The gallery_title property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Nh.Api.Models.EditResponse.EditResponse_gallery_title? GalleryTitle { get; set; }
#nullable restore
#else
        public global::Nhentai.Api.Models.EditResponse.EditResponse_gallery_title GalleryTitle { get; set; }
#endif
        /// <summary>The id property</summary>
        public int? Id { get; set; }
        /// <summary>The removed_tags property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Nh.Api.Models.EditTagInfo>? RemovedTags { get; set; }
#nullable restore
#else
        public List<global::Nhentai.Api.Models.EditTagInfo> RemovedTags { get; set; }
#endif
        /// <summary>The upvotes property</summary>
        public int? Upvotes { get; set; }
        /// <summary>The user_id property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Nh.Api.Models.EditResponse.EditResponse_user_id? UserId { get; set; }
#nullable restore
#else
        public global::Nhentai.Api.Models.EditResponse.EditResponse_user_id UserId { get; set; }
#endif
        /// <summary>The user_username property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Nh.Api.Models.EditResponse.EditResponse_user_username? UserUsername { get; set; }
#nullable restore
#else
        public global::Nhentai.Api.Models.EditResponse.EditResponse_user_username UserUsername { get; set; }
#endif
        /// <summary>The user_vote property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Nh.Api.Models.EditResponse.EditResponse_user_vote? UserVote { get; set; }
#nullable restore
#else
        public global::Nhentai.Api.Models.EditResponse.EditResponse_user_vote UserVote { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Nhentai.Api.Models.EditResponse"/> and sets the default values.
        /// </summary>
        public EditResponse()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Nh.Api.Models.EditResponse"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Nh.Api.Models.EditResponse CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Nh.Api.Models.EditResponse();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "accepted", n => { Accepted = n.GetObjectValue<global::Nh.Api.Models.EditResponse.EditResponse_accepted>(global::Nh.Api.Models.EditResponse.EditResponse_accepted.CreateFromDiscriminatorValue); } },
                { "added_tags", n => { AddedTags = n.GetCollectionOfObjectValues<global::Nh.Api.Models.EditTagInfo>(global::Nh.Api.Models.EditTagInfo.CreateFromDiscriminatorValue)?.AsList(); } },
                { "created_tags", n => { CreatedTags = n.GetCollectionOfObjectValues<global::Nh.Api.Models.CreatedTag>(global::Nh.Api.Models.CreatedTag.CreateFromDiscriminatorValue)?.AsList(); } },
                { "date", n => { Date = n.GetIntValue(); } },
                { "downvotes", n => { Downvotes = n.GetIntValue(); } },
                { "gallery_id", n => { GalleryId = n.GetIntValue(); } },
                { "gallery_title", n => { GalleryTitle = n.GetObjectValue<global::Nh.Api.Models.EditResponse.EditResponse_gallery_title>(global::Nh.Api.Models.EditResponse.EditResponse_gallery_title.CreateFromDiscriminatorValue); } },
                { "id", n => { Id = n.GetIntValue(); } },
                { "removed_tags", n => { RemovedTags = n.GetCollectionOfObjectValues<global::Nh.Api.Models.EditTagInfo>(global::Nh.Api.Models.EditTagInfo.CreateFromDiscriminatorValue)?.AsList(); } },
                { "upvotes", n => { Upvotes = n.GetIntValue(); } },
                { "user_id", n => { UserId = n.GetObjectValue<global::Nh.Api.Models.EditResponse.EditResponse_user_id>(global::Nh.Api.Models.EditResponse.EditResponse_user_id.CreateFromDiscriminatorValue); } },
                { "user_username", n => { UserUsername = n.GetObjectValue<global::Nh.Api.Models.EditResponse.EditResponse_user_username>(global::Nh.Api.Models.EditResponse.EditResponse_user_username.CreateFromDiscriminatorValue); } },
                { "user_vote", n => { UserVote = n.GetObjectValue<global::Nh.Api.Models.EditResponse.EditResponse_user_vote>(global::Nh.Api.Models.EditResponse.EditResponse_user_vote.CreateFromDiscriminatorValue); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteObjectValue<global::Nh.Api.Models.EditResponse.EditResponse_accepted>("accepted", Accepted);
            writer.WriteCollectionOfObjectValues<global::Nh.Api.Models.EditTagInfo>("added_tags", AddedTags);
            writer.WriteCollectionOfObjectValues<global::Nh.Api.Models.CreatedTag>("created_tags", CreatedTags);
            writer.WriteIntValue("date", Date);
            writer.WriteIntValue("downvotes", Downvotes);
            writer.WriteIntValue("gallery_id", GalleryId);
            writer.WriteObjectValue<global::Nh.Api.Models.EditResponse.EditResponse_gallery_title>("gallery_title", GalleryTitle);
            writer.WriteIntValue("id", Id);
            writer.WriteCollectionOfObjectValues<global::Nh.Api.Models.EditTagInfo>("removed_tags", RemovedTags);
            writer.WriteIntValue("upvotes", Upvotes);
            writer.WriteObjectValue<global::Nh.Api.Models.EditResponse.EditResponse_user_id>("user_id", UserId);
            writer.WriteObjectValue<global::Nh.Api.Models.EditResponse.EditResponse_user_username>("user_username", UserUsername);
            writer.WriteObjectValue<global::Nh.Api.Models.EditResponse.EditResponse_user_vote>("user_vote", UserVote);
            writer.WriteAdditionalData(AdditionalData);
        }
        /// <summary>
        /// Composed type wrapper for classes <see cref="bool"/>, <see cref="global::Nh.Api.Models.EditResponse_acceptedMember1"/>
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class EditResponse_accepted : IComposedTypeWrapper, IParsable
        {
            /// <summary>Composed type representation for type <see cref="bool"/></summary>
            public bool? Boolean { get; set; }
            /// <summary>Composed type representation for type <see cref="global::Nh.Api.Models.EditResponse_acceptedMember1"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::Nh.Api.Models.EditResponse_acceptedMember1? EditResponseAcceptedMember1 { get; set; }
#nullable restore
#else
            public global::Nhentai.Api.Models.EditResponse_acceptedMember1 EditResponseAcceptedMember1 { get; set; }
#endif
            /// <summary>
            /// Creates a new instance of the appropriate class based on discriminator value
            /// </summary>
            /// <returns>A <see cref="global::Nhentai.Api.Models.EditResponse.EditResponse_accepted"/></returns>
            /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
            public static global::Nh.Api.Models.EditResponse.EditResponse_accepted CreateFromDiscriminatorValue(IParseNode parseNode)
            {
                if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
                var result = new global::Nh.Api.Models.EditResponse.EditResponse_accepted();
                if(parseNode.GetBoolValue() is bool booleanValue)
                {
                    result.Boolean = booleanValue;
                }
                else {
                    result.EditResponseAcceptedMember1 = new global::Nh.Api.Models.EditResponse_acceptedMember1();
                }
                return result;
            }
            /// <summary>
            /// The deserialization information for the current model
            /// </summary>
            /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
            public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
            {
                if(EditResponseAcceptedMember1 != null)
                {
                    return ParseNodeHelper.MergeDeserializersForIntersectionWrapper(EditResponseAcceptedMember1);
                }
                return new Dictionary<string, Action<IParseNode>>();
            }
            /// <summary>
            /// Serializes information the current object
            /// </summary>
            /// <param name="writer">Serialization writer to use to serialize this model</param>
            public virtual void Serialize(ISerializationWriter writer)
            {
                if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
                if(Boolean != null)
                {
                    writer.WriteBoolValue(null, Boolean);
                }
                else {
                    writer.WriteObjectValue<global::Nh.Api.Models.EditResponse_acceptedMember1>(null, EditResponseAcceptedMember1);
                }
            }
        }
        /// <summary>
        /// Composed type wrapper for classes <see cref="global::Nh.Api.Models.EditResponse_gallery_titleMember1"/>, <see cref="string"/>
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class EditResponse_gallery_title : IComposedTypeWrapper, IParsable
        {
            /// <summary>Composed type representation for type <see cref="global::Nh.Api.Models.EditResponse_gallery_titleMember1"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::Nh.Api.Models.EditResponse_gallery_titleMember1? EditResponseGalleryTitleMember1 { get; set; }
#nullable restore
#else
            public global::Nhentai.Api.Models.EditResponse_gallery_titleMember1 EditResponseGalleryTitleMember1 { get; set; }
#endif
            /// <summary>Composed type representation for type <see cref="string"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public string? String { get; set; }
#nullable restore
#else
            public string String { get; set; }
#endif
            /// <summary>
            /// Creates a new instance of the appropriate class based on discriminator value
            /// </summary>
            /// <returns>A <see cref="global::Nh.Api.Models.EditResponse.EditResponse_gallery_title"/></returns>
            /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
            public static global::Nh.Api.Models.EditResponse.EditResponse_gallery_title CreateFromDiscriminatorValue(IParseNode parseNode)
            {
                if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
                var result = new global::Nh.Api.Models.EditResponse.EditResponse_gallery_title();
                if(parseNode.GetStringValue() is string stringValue)
                {
                    result.String = stringValue;
                }
                else {
                    result.EditResponseGalleryTitleMember1 = new global::Nh.Api.Models.EditResponse_gallery_titleMember1();
                }
                return result;
            }
            /// <summary>
            /// The deserialization information for the current model
            /// </summary>
            /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
            public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
            {
                if(EditResponseGalleryTitleMember1 != null)
                {
                    return ParseNodeHelper.MergeDeserializersForIntersectionWrapper(EditResponseGalleryTitleMember1);
                }
                return new Dictionary<string, Action<IParseNode>>();
            }
            /// <summary>
            /// Serializes information the current object
            /// </summary>
            /// <param name="writer">Serialization writer to use to serialize this model</param>
            public virtual void Serialize(ISerializationWriter writer)
            {
                if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
                if(String != null)
                {
                    writer.WriteStringValue(null, String);
                }
                else {
                    writer.WriteObjectValue<global::Nh.Api.Models.EditResponse_gallery_titleMember1>(null, EditResponseGalleryTitleMember1);
                }
            }
        }
        /// <summary>
        /// Composed type wrapper for classes <see cref="global::Nh.Api.Models.EditResponse_user_idMember1"/>, <see cref="int"/>
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class EditResponse_user_id : IComposedTypeWrapper, IParsable
        {
            /// <summary>Composed type representation for type <see cref="global::Nh.Api.Models.EditResponse_user_idMember1"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::Nh.Api.Models.EditResponse_user_idMember1? EditResponseUserIdMember1 { get; set; }
#nullable restore
#else
            public global::Nhentai.Api.Models.EditResponse_user_idMember1 EditResponseUserIdMember1 { get; set; }
#endif
            /// <summary>Composed type representation for type <see cref="int"/></summary>
            public int? Integer { get; set; }
            /// <summary>
            /// Creates a new instance of the appropriate class based on discriminator value
            /// </summary>
            /// <returns>A <see cref="global::Nh.Api.Models.EditResponse.EditResponse_user_id"/></returns>
            /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
            public static global::Nh.Api.Models.EditResponse.EditResponse_user_id CreateFromDiscriminatorValue(IParseNode parseNode)
            {
                if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
                var result = new global::Nh.Api.Models.EditResponse.EditResponse_user_id();
                if(parseNode.GetIntValue() is int integerValue)
                {
                    result.Integer = integerValue;
                }
                else {
                    result.EditResponseUserIdMember1 = new global::Nh.Api.Models.EditResponse_user_idMember1();
                }
                return result;
            }
            /// <summary>
            /// The deserialization information for the current model
            /// </summary>
            /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
            public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
            {
                if(EditResponseUserIdMember1 != null)
                {
                    return ParseNodeHelper.MergeDeserializersForIntersectionWrapper(EditResponseUserIdMember1);
                }
                return new Dictionary<string, Action<IParseNode>>();
            }
            /// <summary>
            /// Serializes information the current object
            /// </summary>
            /// <param name="writer">Serialization writer to use to serialize this model</param>
            public virtual void Serialize(ISerializationWriter writer)
            {
                if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
                if(Integer != null)
                {
                    writer.WriteIntValue(null, Integer);
                }
                else {
                    writer.WriteObjectValue<global::Nh.Api.Models.EditResponse_user_idMember1>(null, EditResponseUserIdMember1);
                }
            }
        }
        /// <summary>
        /// Composed type wrapper for classes <see cref="global::Nh.Api.Models.EditResponse_user_usernameMember1"/>, <see cref="string"/>
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class EditResponse_user_username : IComposedTypeWrapper, IParsable
        {
            /// <summary>Composed type representation for type <see cref="global::Nh.Api.Models.EditResponse_user_usernameMember1"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::Nh.Api.Models.EditResponse_user_usernameMember1? EditResponseUserUsernameMember1 { get; set; }
#nullable restore
#else
            public global::Nhentai.Api.Models.EditResponse_user_usernameMember1 EditResponseUserUsernameMember1 { get; set; }
#endif
            /// <summary>Composed type representation for type <see cref="string"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public string? String { get; set; }
#nullable restore
#else
            public string String { get; set; }
#endif
            /// <summary>
            /// Creates a new instance of the appropriate class based on discriminator value
            /// </summary>
            /// <returns>A <see cref="global::Nh.Api.Models.EditResponse.EditResponse_user_username"/></returns>
            /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
            public static global::Nh.Api.Models.EditResponse.EditResponse_user_username CreateFromDiscriminatorValue(IParseNode parseNode)
            {
                if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
                var result = new global::Nh.Api.Models.EditResponse.EditResponse_user_username();
                if(parseNode.GetStringValue() is string stringValue)
                {
                    result.String = stringValue;
                }
                else {
                    result.EditResponseUserUsernameMember1 = new global::Nh.Api.Models.EditResponse_user_usernameMember1();
                }
                return result;
            }
            /// <summary>
            /// The deserialization information for the current model
            /// </summary>
            /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
            public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
            {
                if(EditResponseUserUsernameMember1 != null)
                {
                    return ParseNodeHelper.MergeDeserializersForIntersectionWrapper(EditResponseUserUsernameMember1);
                }
                return new Dictionary<string, Action<IParseNode>>();
            }
            /// <summary>
            /// Serializes information the current object
            /// </summary>
            /// <param name="writer">Serialization writer to use to serialize this model</param>
            public virtual void Serialize(ISerializationWriter writer)
            {
                if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
                if(String != null)
                {
                    writer.WriteStringValue(null, String);
                }
                else {
                    writer.WriteObjectValue<global::Nh.Api.Models.EditResponse_user_usernameMember1>(null, EditResponseUserUsernameMember1);
                }
            }
        }
        /// <summary>
        /// Composed type wrapper for classes <see cref="bool"/>, <see cref="global::Nh.Api.Models.EditResponse_user_voteMember1"/>
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class EditResponse_user_vote : IComposedTypeWrapper, IParsable
        {
            /// <summary>Composed type representation for type <see cref="bool"/></summary>
            public bool? Boolean { get; set; }
            /// <summary>Composed type representation for type <see cref="global::Nh.Api.Models.EditResponse_user_voteMember1"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::Nh.Api.Models.EditResponse_user_voteMember1? EditResponseUserVoteMember1 { get; set; }
#nullable restore
#else
            public global::Nhentai.Api.Models.EditResponse_user_voteMember1 EditResponseUserVoteMember1 { get; set; }
#endif
            /// <summary>
            /// Creates a new instance of the appropriate class based on discriminator value
            /// </summary>
            /// <returns>A <see cref="global::Nhentai.Api.Models.EditResponse.EditResponse_user_vote"/></returns>
            /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
            public static global::Nh.Api.Models.EditResponse.EditResponse_user_vote CreateFromDiscriminatorValue(IParseNode parseNode)
            {
                if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
                var result = new global::Nh.Api.Models.EditResponse.EditResponse_user_vote();
                if(parseNode.GetBoolValue() is bool booleanValue)
                {
                    result.Boolean = booleanValue;
                }
                else {
                    result.EditResponseUserVoteMember1 = new global::Nh.Api.Models.EditResponse_user_voteMember1();
                }
                return result;
            }
            /// <summary>
            /// The deserialization information for the current model
            /// </summary>
            /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
            public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
            {
                if(EditResponseUserVoteMember1 != null)
                {
                    return ParseNodeHelper.MergeDeserializersForIntersectionWrapper(EditResponseUserVoteMember1);
                }
                return new Dictionary<string, Action<IParseNode>>();
            }
            /// <summary>
            /// Serializes information the current object
            /// </summary>
            /// <param name="writer">Serialization writer to use to serialize this model</param>
            public virtual void Serialize(ISerializationWriter writer)
            {
                if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
                if(Boolean != null)
                {
                    writer.WriteBoolValue(null, Boolean);
                }
                else {
                    writer.WriteObjectValue<global::Nh.Api.Models.EditResponse_user_voteMember1>(null, EditResponseUserVoteMember1);
                }
            }
        }
    }
}
#pragma warning restore CS0618
