// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Nh.Api.Models
{
    /// <summary>
    /// Response for favorite/unfavorite actions.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class FavoriteResponse : IAdditionalDataHolder, IParsable
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The favorited property</summary>
        public bool? Favorited { get; set; }
        /// <summary>The num_favorites property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Nh.Api.Models.FavoriteResponse.FavoriteResponse_num_favorites? NumFavorites { get; set; }
#nullable restore
#else
        public global::Nhentai.Api.Models.FavoriteResponse.FavoriteResponse_num_favorites NumFavorites { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Nhentai.Api.Models.FavoriteResponse"/> and sets the default values.
        /// </summary>
        public FavoriteResponse()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Nh.Api.Models.FavoriteResponse"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Nh.Api.Models.FavoriteResponse CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Nh.Api.Models.FavoriteResponse();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "favorited", n => { Favorited = n.GetBoolValue(); } },
                { "num_favorites", n => { NumFavorites = n.GetObjectValue<global::Nh.Api.Models.FavoriteResponse.FavoriteResponse_num_favorites>(global::Nh.Api.Models.FavoriteResponse.FavoriteResponse_num_favorites.CreateFromDiscriminatorValue); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteBoolValue("favorited", Favorited);
            writer.WriteObjectValue<global::Nh.Api.Models.FavoriteResponse.FavoriteResponse_num_favorites>("num_favorites", NumFavorites);
            writer.WriteAdditionalData(AdditionalData);
        }
        /// <summary>
        /// Composed type wrapper for classes <see cref="global::Nh.Api.Models.FavoriteResponse_num_favoritesMember1"/>, <see cref="int"/>
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class FavoriteResponse_num_favorites : IComposedTypeWrapper, IParsable
        {
            /// <summary>Composed type representation for type <see cref="global::Nh.Api.Models.FavoriteResponse_num_favoritesMember1"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::Nh.Api.Models.FavoriteResponse_num_favoritesMember1? FavoriteResponseNumFavoritesMember1 { get; set; }
#nullable restore
#else
            public global::Nhentai.Api.Models.FavoriteResponse_num_favoritesMember1 FavoriteResponseNumFavoritesMember1 { get; set; }
#endif
            /// <summary>Composed type representation for type <see cref="int"/></summary>
            public int? Integer { get; set; }
            /// <summary>
            /// Creates a new instance of the appropriate class based on discriminator value
            /// </summary>
            /// <returns>A <see cref="global::Nh.Api.Models.FavoriteResponse.FavoriteResponse_num_favorites"/></returns>
            /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
            public static global::Nh.Api.Models.FavoriteResponse.FavoriteResponse_num_favorites CreateFromDiscriminatorValue(IParseNode parseNode)
            {
                if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
                var result = new global::Nh.Api.Models.FavoriteResponse.FavoriteResponse_num_favorites();
                if(parseNode.GetIntValue() is int integerValue)
                {
                    result.Integer = integerValue;
                }
                else {
                    result.FavoriteResponseNumFavoritesMember1 = new global::Nh.Api.Models.FavoriteResponse_num_favoritesMember1();
                }
                return result;
            }
            /// <summary>
            /// The deserialization information for the current model
            /// </summary>
            /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
            public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
            {
                if(FavoriteResponseNumFavoritesMember1 != null)
                {
                    return ParseNodeHelper.MergeDeserializersForIntersectionWrapper(FavoriteResponseNumFavoritesMember1);
                }
                return new Dictionary<string, Action<IParseNode>>();
            }
            /// <summary>
            /// Serializes information the current object
            /// </summary>
            /// <param name="writer">Serialization writer to use to serialize this model</param>
            public virtual void Serialize(ISerializationWriter writer)
            {
                if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
                if(Integer != null)
                {
                    writer.WriteIntValue(null, Integer);
                }
                else {
                    writer.WriteObjectValue<global::Nh.Api.Models.FavoriteResponse_num_favoritesMember1>(null, FavoriteResponseNumFavoritesMember1);
                }
            }
        }
    }
}
#pragma warning restore CS0618
