// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Nh.Api.Models
{
    /// <summary>
    /// Request body for submitting a gallery edit.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class SubmitEditRequest : IAdditionalDataHolder, IParsable
    {
        /// <summary>The added_tags property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<int?>? AddedTags { get; set; }
#nullable restore
#else
        public List<int?> AddedTags { get; set; }
#endif
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The created_tags property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Nh.Api.Models.CreatedTag>? CreatedTags { get; set; }
#nullable restore
#else
        public List<global::Nhentai.Api.Models.CreatedTag> CreatedTags { get; set; }
#endif
        /// <summary>The removed_tags property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<int?>? RemovedTags { get; set; }
#nullable restore
#else
        public List<int?> RemovedTags { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Nh.Api.Models.SubmitEditRequest"/> and sets the default values.
        /// </summary>
        public SubmitEditRequest()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Nh.Api.Models.SubmitEditRequest"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Nh.Api.Models.SubmitEditRequest CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Nh.Api.Models.SubmitEditRequest();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "added_tags", n => { AddedTags = n.GetCollectionOfPrimitiveValues<int?>()?.AsList(); } },
                { "created_tags", n => { CreatedTags = n.GetCollectionOfObjectValues<global::Nh.Api.Models.CreatedTag>(global::Nh.Api.Models.CreatedTag.CreateFromDiscriminatorValue)?.AsList(); } },
                { "removed_tags", n => { RemovedTags = n.GetCollectionOfPrimitiveValues<int?>()?.AsList(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteCollectionOfPrimitiveValues<int?>("added_tags", AddedTags);
            writer.WriteCollectionOfObjectValues<global::Nh.Api.Models.CreatedTag>("created_tags", CreatedTags);
            writer.WriteCollectionOfPrimitiveValues<int?>("removed_tags", RemovedTags);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
