// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Nh.Api.Models
{
    /// <summary>
    /// Paginated tag response with optional alphabet mapping.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class TagPaginatedResponse : IAdditionalDataHolder, IParsable
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The alphabet property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public UntypedNode? Alphabet { get; set; }
#nullable restore
#else
        public UntypedNode Alphabet { get; set; }
#endif
        /// <summary>The num_pages property</summary>
        public int? NumPages { get; set; }
        /// <summary>The per_page property</summary>
        public int? PerPage { get; set; }
        /// <summary>The result property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Nh.Api.Models.TagResponse>? Result { get; set; }
#nullable restore
#else
        public List<global::Nhentai.Api.Models.TagResponse> Result { get; set; }
#endif
        /// <summary>The total property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Nh.Api.Models.TagPaginatedResponse.TagPaginatedResponse_total? Total { get; set; }
#nullable restore
#else
        public global::Nhentai.Api.Models.TagPaginatedResponse.TagPaginatedResponse_total Total { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Nhentai.Api.Models.TagPaginatedResponse"/> and sets the default values.
        /// </summary>
        public TagPaginatedResponse()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Nh.Api.Models.TagPaginatedResponse"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Nh.Api.Models.TagPaginatedResponse CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Nh.Api.Models.TagPaginatedResponse();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "alphabet", n => { Alphabet = n.GetObjectValue<UntypedNode>(UntypedNode.CreateFromDiscriminatorValue); } },
                { "num_pages", n => { NumPages = n.GetIntValue(); } },
                { "per_page", n => { PerPage = n.GetIntValue(); } },
                { "result", n => { Result = n.GetCollectionOfObjectValues<global::Nh.Api.Models.TagResponse>(global::Nh.Api.Models.TagResponse.CreateFromDiscriminatorValue)?.AsList(); } },
                { "total", n => { Total = n.GetObjectValue<global::Nh.Api.Models.TagPaginatedResponse.TagPaginatedResponse_total>(global::Nh.Api.Models.TagPaginatedResponse.TagPaginatedResponse_total.CreateFromDiscriminatorValue); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteObjectValue<UntypedNode>("alphabet", Alphabet);
            writer.WriteIntValue("num_pages", NumPages);
            writer.WriteIntValue("per_page", PerPage);
            writer.WriteCollectionOfObjectValues<global::Nh.Api.Models.TagResponse>("result", Result);
            writer.WriteObjectValue<global::Nh.Api.Models.TagPaginatedResponse.TagPaginatedResponse_total>("total", Total);
            writer.WriteAdditionalData(AdditionalData);
        }
        /// <summary>
        /// Composed type wrapper for classes <see cref="global::Nh.Api.Models.TagPaginatedResponse_totalMember1"/>, <see cref="int"/>
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class TagPaginatedResponse_total : IComposedTypeWrapper, IParsable
        {
            /// <summary>Composed type representation for type <see cref="int"/></summary>
            public int? Integer { get; set; }
            /// <summary>Composed type representation for type <see cref="global::Nh.Api.Models.TagPaginatedResponse_totalMember1"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::Nh.Api.Models.TagPaginatedResponse_totalMember1? TagPaginatedResponseTotalMember1 { get; set; }
#nullable restore
#else
            public global::Nhentai.Api.Models.TagPaginatedResponse_totalMember1 TagPaginatedResponseTotalMember1 { get; set; }
#endif
            /// <summary>
            /// Creates a new instance of the appropriate class based on discriminator value
            /// </summary>
            /// <returns>A <see cref="global::Nhentai.Api.Models.TagPaginatedResponse.TagPaginatedResponse_total"/></returns>
            /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
            public static global::Nh.Api.Models.TagPaginatedResponse.TagPaginatedResponse_total CreateFromDiscriminatorValue(IParseNode parseNode)
            {
                if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
                var result = new global::Nh.Api.Models.TagPaginatedResponse.TagPaginatedResponse_total();
                if(parseNode.GetIntValue() is int integerValue)
                {
                    result.Integer = integerValue;
                }
                else {
                    result.TagPaginatedResponseTotalMember1 = new global::Nh.Api.Models.TagPaginatedResponse_totalMember1();
                }
                return result;
            }
            /// <summary>
            /// The deserialization information for the current model
            /// </summary>
            /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
            public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
            {
                if(TagPaginatedResponseTotalMember1 != null)
                {
                    return ParseNodeHelper.MergeDeserializersForIntersectionWrapper(TagPaginatedResponseTotalMember1);
                }
                return new Dictionary<string, Action<IParseNode>>();
            }
            /// <summary>
            /// Serializes information the current object
            /// </summary>
            /// <param name="writer">Serialization writer to use to serialize this model</param>
            public virtual void Serialize(ISerializationWriter writer)
            {
                if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
                if(Integer != null)
                {
                    writer.WriteIntValue(null, Integer);
                }
                else {
                    writer.WriteObjectValue<global::Nh.Api.Models.TagPaginatedResponse_totalMember1>(null, TagPaginatedResponseTotalMember1);
                }
            }
        }
    }
}
#pragma warning restore CS0618
