// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using Nh.Api.Api.V2.Favorites.RandomNamespace;
using Nh.Api.Models;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace Nh.Api.Api.V2.Favorites
{
    /// <summary>
    /// Builds and executes requests for operations under \api\v2\favorites
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class FavoritesRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The random property</summary>
        public global::Nh.Api.Api.V2.Favorites.RandomNamespace.RandomRequestBuilder Random
        {
            get => new global::Nh.Api.Api.V2.Favorites.RandomNamespace.RandomRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Nh.Api.Api.V2.Favorites.FavoritesRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public FavoritesRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/v2/favorites{?page*,q*}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Nh.Api.Api.V2.Favorites.FavoritesRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public FavoritesRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/v2/favorites{?page*,q*}", rawUrl)
        {
        }
        /// <summary>
        /// Get the authenticated user&apos;s favorite galleries.---**Auth:** User Token or API Key**Rate limits:**- 15/1min per user- 15/1min per API key owner
        /// </summary>
        /// <returns>A <see cref="global::Nh.Api.Models.PaginatedResponse_GalleryListItem_"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::Nh.Api.Models.ErrorResponse">When receiving a 401 status code</exception>
        /// <exception cref="global::Nh.Api.Models.HTTPValidationError">When receiving a 422 status code</exception>
        /// <exception cref="global::Nh.Api.Models.ErrorResponse">When receiving a 429 status code</exception>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::Nh.Api.Models.PaginatedResponse_GalleryListItem_?> GetAsync(Action<RequestConfiguration<global::Nh.Api.Api.V2.Favorites.FavoritesRequestBuilder.FavoritesRequestBuilderGetQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::Nhentai.Api.Models.PaginatedResponse_GalleryListItem_> GetAsync(Action<RequestConfiguration<global::Nhentai.Api.Api.V2.Favorites.FavoritesRequestBuilder.FavoritesRequestBuilderGetQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToGetRequestInformation(requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "401", global::Nh.Api.Models.ErrorResponse.CreateFromDiscriminatorValue },
                { "422", global::Nh.Api.Models.HTTPValidationError.CreateFromDiscriminatorValue },
                { "429", global::Nh.Api.Models.ErrorResponse.CreateFromDiscriminatorValue },
            };
            return await RequestAdapter.SendAsync<global::Nh.Api.Models.PaginatedResponse_GalleryListItem_>(requestInfo, global::Nh.Api.Models.PaginatedResponse_GalleryListItem_.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Get the authenticated user&apos;s favorite galleries.---**Auth:** User Token or API Key**Rate limits:**- 15/1min per user- 15/1min per API key owner
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::Nh.Api.Api.V2.Favorites.FavoritesRequestBuilder.FavoritesRequestBuilderGetQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::Nhentai.Api.Api.V2.Favorites.FavoritesRequestBuilder.FavoritesRequestBuilderGetQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.GET, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::Nh.Api.Api.V2.Favorites.FavoritesRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::Nh.Api.Api.V2.Favorites.FavoritesRequestBuilder WithUrl(string rawUrl)
        {
            return new global::Nh.Api.Api.V2.Favorites.FavoritesRequestBuilder(rawUrl, RequestAdapter);
        }
        /// <summary>
        /// Get the authenticated user&apos;s favorite galleries.---**Auth:** User Token or API Key**Rate limits:**- 15/1min per user- 15/1min per API key owner
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class FavoritesRequestBuilderGetQueryParameters 
        {
            [QueryParameter("page")]
            public int? Page { get; set; }
            /// <summary>Search within favorites</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("q")]
            public string? Q { get; set; }
#nullable restore
#else
            [QueryParameter("q")]
            public string Q { get; set; }
#endif
        }
        /// <summary>
        /// Configuration for the request such as headers, query parameters, and middleware options.
        /// </summary>
        [Obsolete("This class is deprecated. Please use the generic RequestConfiguration class generated by the generator.")]
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class FavoritesRequestBuilderGetRequestConfiguration : RequestConfiguration<global::Nh.Api.Api.V2.Favorites.FavoritesRequestBuilder.FavoritesRequestBuilderGetQueryParameters>
        {
        }
    }
}
#pragma warning restore CS0618
