// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Nhentai.Api.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class Body_create_comment_api_v2_galleries__gallery_id__comments_post : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>Comment text</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Body { get; set; }
#nullable restore
#else
        public string Body { get; set; }
#endif
        /// <summary>CAPTCHA response token</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Nhentai.Api.Models.Body_create_comment_api_v2_galleries__gallery_id__comments_post.Body_create_comment_api_v2_galleries__gallery_id__comments_post_captcha_response? CaptchaResponse { get; set; }
#nullable restore
#else
        public global::Nhentai.Api.Models.Body_create_comment_api_v2_galleries__gallery_id__comments_post.Body_create_comment_api_v2_galleries__gallery_id__comments_post_captcha_response CaptchaResponse { get; set; }
#endif
        /// <summary>PoW challenge from GET /api/v2/pow</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? PowChallenge { get; set; }
#nullable restore
#else
        public string PowChallenge { get; set; }
#endif
        /// <summary>Nonce that solves the PoW challenge</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? PowNonce { get; set; }
#nullable restore
#else
        public string PowNonce { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Nhentai.Api.Models.Body_create_comment_api_v2_galleries__gallery_id__comments_post"/> and sets the default values.
        /// </summary>
        public Body_create_comment_api_v2_galleries__gallery_id__comments_post()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Nhentai.Api.Models.Body_create_comment_api_v2_galleries__gallery_id__comments_post"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Nhentai.Api.Models.Body_create_comment_api_v2_galleries__gallery_id__comments_post CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Nhentai.Api.Models.Body_create_comment_api_v2_galleries__gallery_id__comments_post();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "body", n => { Body = n.GetStringValue(); } },
                { "captcha_response", n => { CaptchaResponse = n.GetObjectValue<global::Nhentai.Api.Models.Body_create_comment_api_v2_galleries__gallery_id__comments_post.Body_create_comment_api_v2_galleries__gallery_id__comments_post_captcha_response>(global::Nhentai.Api.Models.Body_create_comment_api_v2_galleries__gallery_id__comments_post.Body_create_comment_api_v2_galleries__gallery_id__comments_post_captcha_response.CreateFromDiscriminatorValue); } },
                { "pow_challenge", n => { PowChallenge = n.GetStringValue(); } },
                { "pow_nonce", n => { PowNonce = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("body", Body);
            writer.WriteObjectValue<global::Nhentai.Api.Models.Body_create_comment_api_v2_galleries__gallery_id__comments_post.Body_create_comment_api_v2_galleries__gallery_id__comments_post_captcha_response>("captcha_response", CaptchaResponse);
            writer.WriteStringValue("pow_challenge", PowChallenge);
            writer.WriteStringValue("pow_nonce", PowNonce);
            writer.WriteAdditionalData(AdditionalData);
        }
        /// <summary>
        /// Composed type wrapper for classes <see cref="global::Nhentai.Api.Models.Body_create_comment_api_v2_galleries__gallery_id__comments_post_captcha_responseMember1"/>, <see cref="string"/>
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class Body_create_comment_api_v2_galleries__gallery_id__comments_post_captcha_response : IComposedTypeWrapper, IParsable
        {
            /// <summary>Composed type representation for type <see cref="global::Nhentai.Api.Models.Body_create_comment_api_v2_galleries__gallery_id__comments_post_captcha_responseMember1"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::Nhentai.Api.Models.Body_create_comment_api_v2_galleries__gallery_id__comments_post_captcha_responseMember1? BodyCreateCommentApiV2GalleriesGalleryIdCommentsPostCaptchaResponseMember1 { get; set; }
#nullable restore
#else
            public global::Nhentai.Api.Models.Body_create_comment_api_v2_galleries__gallery_id__comments_post_captcha_responseMember1 BodyCreateCommentApiV2GalleriesGalleryIdCommentsPostCaptchaResponseMember1 { get; set; }
#endif
            /// <summary>Composed type representation for type <see cref="string"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public string? String { get; set; }
#nullable restore
#else
            public string String { get; set; }
#endif
            /// <summary>
            /// Creates a new instance of the appropriate class based on discriminator value
            /// </summary>
            /// <returns>A <see cref="global::Nhentai.Api.Models.Body_create_comment_api_v2_galleries__gallery_id__comments_post.Body_create_comment_api_v2_galleries__gallery_id__comments_post_captcha_response"/></returns>
            /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
            public static global::Nhentai.Api.Models.Body_create_comment_api_v2_galleries__gallery_id__comments_post.Body_create_comment_api_v2_galleries__gallery_id__comments_post_captcha_response CreateFromDiscriminatorValue(IParseNode parseNode)
            {
                if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
                var result = new global::Nhentai.Api.Models.Body_create_comment_api_v2_galleries__gallery_id__comments_post.Body_create_comment_api_v2_galleries__gallery_id__comments_post_captcha_response();
                if(parseNode.GetStringValue() is string stringValue)
                {
                    result.String = stringValue;
                }
                else {
                    result.BodyCreateCommentApiV2GalleriesGalleryIdCommentsPostCaptchaResponseMember1 = new global::Nhentai.Api.Models.Body_create_comment_api_v2_galleries__gallery_id__comments_post_captcha_responseMember1();
                }
                return result;
            }
            /// <summary>
            /// The deserialization information for the current model
            /// </summary>
            /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
            public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
            {
                if(BodyCreateCommentApiV2GalleriesGalleryIdCommentsPostCaptchaResponseMember1 != null)
                {
                    return ParseNodeHelper.MergeDeserializersForIntersectionWrapper(BodyCreateCommentApiV2GalleriesGalleryIdCommentsPostCaptchaResponseMember1);
                }
                return new Dictionary<string, Action<IParseNode>>();
            }
            /// <summary>
            /// Serializes information the current object
            /// </summary>
            /// <param name="writer">Serialization writer to use to serialize this model</param>
            public virtual void Serialize(ISerializationWriter writer)
            {
                if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
                if(String != null)
                {
                    writer.WriteStringValue(null, String);
                }
                else {
                    writer.WriteObjectValue<global::Nhentai.Api.Models.Body_create_comment_api_v2_galleries__gallery_id__comments_post_captcha_responseMember1>(null, BodyCreateCommentApiV2GalleriesGalleryIdCommentsPostCaptchaResponseMember1);
                }
            }
        }
    }
}
#pragma warning restore CS0618
