// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Nhentai.Api.Models
{
    /// <summary>
    /// Lightweight gallery for list views.Used in search results, tag listings, homepage.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class GalleryListItem : IAdditionalDataHolder, IParsable
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The blacklisted property</summary>
        public bool? Blacklisted { get; set; }
        /// <summary>The english_title property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? EnglishTitle { get; set; }
#nullable restore
#else
        public string EnglishTitle { get; set; }
#endif
        /// <summary>The id property</summary>
        public int? Id { get; set; }
        /// <summary>The japanese_title property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Nhentai.Api.Models.GalleryListItem.GalleryListItem_japanese_title? JapaneseTitle { get; set; }
#nullable restore
#else
        public global::Nhentai.Api.Models.GalleryListItem.GalleryListItem_japanese_title JapaneseTitle { get; set; }
#endif
        /// <summary>The media_id property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? MediaId { get; set; }
#nullable restore
#else
        public string MediaId { get; set; }
#endif
        /// <summary>The num_pages property</summary>
        public int? NumPages { get; set; }
        /// <summary>The tag_ids property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<int?>? TagIds { get; set; }
#nullable restore
#else
        public List<int?> TagIds { get; set; }
#endif
        /// <summary>The thumbnail property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Thumbnail { get; set; }
#nullable restore
#else
        public string Thumbnail { get; set; }
#endif
        /// <summary>The thumbnail_height property</summary>
        public int? ThumbnailHeight { get; set; }
        /// <summary>The thumbnail_width property</summary>
        public int? ThumbnailWidth { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::Nhentai.Api.Models.GalleryListItem"/> and sets the default values.
        /// </summary>
        public GalleryListItem()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Nhentai.Api.Models.GalleryListItem"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Nhentai.Api.Models.GalleryListItem CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Nhentai.Api.Models.GalleryListItem();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "blacklisted", n => { Blacklisted = n.GetBoolValue(); } },
                { "english_title", n => { EnglishTitle = n.GetStringValue(); } },
                { "id", n => { Id = n.GetIntValue(); } },
                { "japanese_title", n => { JapaneseTitle = n.GetObjectValue<global::Nhentai.Api.Models.GalleryListItem.GalleryListItem_japanese_title>(global::Nhentai.Api.Models.GalleryListItem.GalleryListItem_japanese_title.CreateFromDiscriminatorValue); } },
                { "media_id", n => { MediaId = n.GetStringValue(); } },
                { "num_pages", n => { NumPages = n.GetIntValue(); } },
                { "tag_ids", n => { TagIds = n.GetCollectionOfPrimitiveValues<int?>()?.AsList(); } },
                { "thumbnail", n => { Thumbnail = n.GetStringValue(); } },
                { "thumbnail_height", n => { ThumbnailHeight = n.GetIntValue(); } },
                { "thumbnail_width", n => { ThumbnailWidth = n.GetIntValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteBoolValue("blacklisted", Blacklisted);
            writer.WriteStringValue("english_title", EnglishTitle);
            writer.WriteIntValue("id", Id);
            writer.WriteObjectValue<global::Nhentai.Api.Models.GalleryListItem.GalleryListItem_japanese_title>("japanese_title", JapaneseTitle);
            writer.WriteStringValue("media_id", MediaId);
            writer.WriteIntValue("num_pages", NumPages);
            writer.WriteCollectionOfPrimitiveValues<int?>("tag_ids", TagIds);
            writer.WriteStringValue("thumbnail", Thumbnail);
            writer.WriteIntValue("thumbnail_height", ThumbnailHeight);
            writer.WriteIntValue("thumbnail_width", ThumbnailWidth);
            writer.WriteAdditionalData(AdditionalData);
        }
        /// <summary>
        /// Composed type wrapper for classes <see cref="global::Nhentai.Api.Models.GalleryListItem_japanese_titleMember1"/>, <see cref="string"/>
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class GalleryListItem_japanese_title : IComposedTypeWrapper, IParsable
        {
            /// <summary>Composed type representation for type <see cref="global::Nhentai.Api.Models.GalleryListItem_japanese_titleMember1"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::Nhentai.Api.Models.GalleryListItem_japanese_titleMember1? GalleryListItemJapaneseTitleMember1 { get; set; }
#nullable restore
#else
            public global::Nhentai.Api.Models.GalleryListItem_japanese_titleMember1 GalleryListItemJapaneseTitleMember1 { get; set; }
#endif
            /// <summary>Composed type representation for type <see cref="string"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public string? String { get; set; }
#nullable restore
#else
            public string String { get; set; }
#endif
            /// <summary>
            /// Creates a new instance of the appropriate class based on discriminator value
            /// </summary>
            /// <returns>A <see cref="global::Nhentai.Api.Models.GalleryListItem.GalleryListItem_japanese_title"/></returns>
            /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
            public static global::Nhentai.Api.Models.GalleryListItem.GalleryListItem_japanese_title CreateFromDiscriminatorValue(IParseNode parseNode)
            {
                if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
                var result = new global::Nhentai.Api.Models.GalleryListItem.GalleryListItem_japanese_title();
                if(parseNode.GetStringValue() is string stringValue)
                {
                    result.String = stringValue;
                }
                else {
                    result.GalleryListItemJapaneseTitleMember1 = new global::Nhentai.Api.Models.GalleryListItem_japanese_titleMember1();
                }
                return result;
            }
            /// <summary>
            /// The deserialization information for the current model
            /// </summary>
            /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
            public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
            {
                if(GalleryListItemJapaneseTitleMember1 != null)
                {
                    return ParseNodeHelper.MergeDeserializersForIntersectionWrapper(GalleryListItemJapaneseTitleMember1);
                }
                return new Dictionary<string, Action<IParseNode>>();
            }
            /// <summary>
            /// Serializes information the current object
            /// </summary>
            /// <param name="writer">Serialization writer to use to serialize this model</param>
            public virtual void Serialize(ISerializationWriter writer)
            {
                if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
                if(String != null)
                {
                    writer.WriteStringValue(null, String);
                }
                else {
                    writer.WriteObjectValue<global::Nhentai.Api.Models.GalleryListItem_japanese_titleMember1>(null, GalleryListItemJapaneseTitleMember1);
                }
            }
        }
    }
}
#pragma warning restore CS0618
