// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Nhentai.Api.Models
{
    /// <summary>
    /// Gallery detail with optional included data (comments, related, favorite).
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class GalleryDetailResponse : IAdditionalDataHolder, IParsable
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The comments property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Nhentai.Api.Models.CommentResponse>? Comments { get; set; }
#nullable restore
#else
        public List<global::Nhentai.Api.Models.CommentResponse> Comments { get; set; }
#endif
        /// <summary>Cover/thumbnail image with path and dimensions.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Nhentai.Api.Models.CoverInfo? Cover { get; set; }
#nullable restore
#else
        public global::Nhentai.Api.Models.CoverInfo Cover { get; set; }
#endif
        /// <summary>The id property</summary>
        public int? Id { get; set; }
        /// <summary>The is_favorited property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Nhentai.Api.Models.GalleryDetailResponse.GalleryDetailResponse_is_favorited? IsFavorited { get; set; }
#nullable restore
#else
        public global::Nhentai.Api.Models.GalleryDetailResponse.GalleryDetailResponse_is_favorited IsFavorited { get; set; }
#endif
        /// <summary>The media_id property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? MediaId { get; set; }
#nullable restore
#else
        public string MediaId { get; set; }
#endif
        /// <summary>The num_favorites property</summary>
        public int? NumFavorites { get; set; }
        /// <summary>The num_pages property</summary>
        public int? NumPages { get; set; }
        /// <summary>The pages property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Nhentai.Api.Models.PageInfo>? Pages { get; set; }
#nullable restore
#else
        public List<global::Nhentai.Api.Models.PageInfo> Pages { get; set; }
#endif
        /// <summary>The related property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Nhentai.Api.Models.GalleryListItem>? Related { get; set; }
#nullable restore
#else
        public List<global::Nhentai.Api.Models.GalleryListItem> Related { get; set; }
#endif
        /// <summary>The scanlator property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Scanlator { get; set; }
#nullable restore
#else
        public string Scanlator { get; set; }
#endif
        /// <summary>The tags property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Nhentai.Api.Models.TagResponse>? Tags { get; set; }
#nullable restore
#else
        public List<global::Nhentai.Api.Models.TagResponse> Tags { get; set; }
#endif
        /// <summary>Cover/thumbnail image with path and dimensions.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Nhentai.Api.Models.CoverInfo? Thumbnail { get; set; }
#nullable restore
#else
        public global::Nhentai.Api.Models.CoverInfo Thumbnail { get; set; }
#endif
        /// <summary>Gallery title in multiple languages.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Nhentai.Api.Models.GalleryTitle? Title { get; set; }
#nullable restore
#else
        public global::Nhentai.Api.Models.GalleryTitle Title { get; set; }
#endif
        /// <summary>The upload_date property</summary>
        public int? UploadDate { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::Nhentai.Api.Models.GalleryDetailResponse"/> and sets the default values.
        /// </summary>
        public GalleryDetailResponse()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Nhentai.Api.Models.GalleryDetailResponse"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Nhentai.Api.Models.GalleryDetailResponse CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Nhentai.Api.Models.GalleryDetailResponse();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "comments", n => { Comments = n.GetCollectionOfObjectValues<global::Nhentai.Api.Models.CommentResponse>(global::Nhentai.Api.Models.CommentResponse.CreateFromDiscriminatorValue)?.AsList(); } },
                { "cover", n => { Cover = n.GetObjectValue<global::Nhentai.Api.Models.CoverInfo>(global::Nhentai.Api.Models.CoverInfo.CreateFromDiscriminatorValue); } },
                { "id", n => { Id = n.GetIntValue(); } },
                { "is_favorited", n => { IsFavorited = n.GetObjectValue<global::Nhentai.Api.Models.GalleryDetailResponse.GalleryDetailResponse_is_favorited>(global::Nhentai.Api.Models.GalleryDetailResponse.GalleryDetailResponse_is_favorited.CreateFromDiscriminatorValue); } },
                { "media_id", n => { MediaId = n.GetStringValue(); } },
                { "num_favorites", n => { NumFavorites = n.GetIntValue(); } },
                { "num_pages", n => { NumPages = n.GetIntValue(); } },
                { "pages", n => { Pages = n.GetCollectionOfObjectValues<global::Nhentai.Api.Models.PageInfo>(global::Nhentai.Api.Models.PageInfo.CreateFromDiscriminatorValue)?.AsList(); } },
                { "related", n => { Related = n.GetCollectionOfObjectValues<global::Nhentai.Api.Models.GalleryListItem>(global::Nhentai.Api.Models.GalleryListItem.CreateFromDiscriminatorValue)?.AsList(); } },
                { "scanlator", n => { Scanlator = n.GetStringValue(); } },
                { "tags", n => { Tags = n.GetCollectionOfObjectValues<global::Nhentai.Api.Models.TagResponse>(global::Nhentai.Api.Models.TagResponse.CreateFromDiscriminatorValue)?.AsList(); } },
                { "thumbnail", n => { Thumbnail = n.GetObjectValue<global::Nhentai.Api.Models.CoverInfo>(global::Nhentai.Api.Models.CoverInfo.CreateFromDiscriminatorValue); } },
                { "title", n => { Title = n.GetObjectValue<global::Nhentai.Api.Models.GalleryTitle>(global::Nhentai.Api.Models.GalleryTitle.CreateFromDiscriminatorValue); } },
                { "upload_date", n => { UploadDate = n.GetIntValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteCollectionOfObjectValues<global::Nhentai.Api.Models.CommentResponse>("comments", Comments);
            writer.WriteObjectValue<global::Nhentai.Api.Models.CoverInfo>("cover", Cover);
            writer.WriteIntValue("id", Id);
            writer.WriteObjectValue<global::Nhentai.Api.Models.GalleryDetailResponse.GalleryDetailResponse_is_favorited>("is_favorited", IsFavorited);
            writer.WriteStringValue("media_id", MediaId);
            writer.WriteIntValue("num_favorites", NumFavorites);
            writer.WriteIntValue("num_pages", NumPages);
            writer.WriteCollectionOfObjectValues<global::Nhentai.Api.Models.PageInfo>("pages", Pages);
            writer.WriteCollectionOfObjectValues<global::Nhentai.Api.Models.GalleryListItem>("related", Related);
            writer.WriteStringValue("scanlator", Scanlator);
            writer.WriteCollectionOfObjectValues<global::Nhentai.Api.Models.TagResponse>("tags", Tags);
            writer.WriteObjectValue<global::Nhentai.Api.Models.CoverInfo>("thumbnail", Thumbnail);
            writer.WriteObjectValue<global::Nhentai.Api.Models.GalleryTitle>("title", Title);
            writer.WriteIntValue("upload_date", UploadDate);
            writer.WriteAdditionalData(AdditionalData);
        }
        /// <summary>
        /// Composed type wrapper for classes <see cref="bool"/>, <see cref="global::Nhentai.Api.Models.GalleryDetailResponse_is_favoritedMember1"/>
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class GalleryDetailResponse_is_favorited : IComposedTypeWrapper, IParsable
        {
            /// <summary>Composed type representation for type <see cref="bool"/></summary>
            public bool? Boolean { get; set; }
            /// <summary>Composed type representation for type <see cref="global::Nhentai.Api.Models.GalleryDetailResponse_is_favoritedMember1"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::Nhentai.Api.Models.GalleryDetailResponse_is_favoritedMember1? GalleryDetailResponseIsFavoritedMember1 { get; set; }
#nullable restore
#else
            public global::Nhentai.Api.Models.GalleryDetailResponse_is_favoritedMember1 GalleryDetailResponseIsFavoritedMember1 { get; set; }
#endif
            /// <summary>
            /// Creates a new instance of the appropriate class based on discriminator value
            /// </summary>
            /// <returns>A <see cref="global::Nhentai.Api.Models.GalleryDetailResponse.GalleryDetailResponse_is_favorited"/></returns>
            /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
            public static global::Nhentai.Api.Models.GalleryDetailResponse.GalleryDetailResponse_is_favorited CreateFromDiscriminatorValue(IParseNode parseNode)
            {
                if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
                var result = new global::Nhentai.Api.Models.GalleryDetailResponse.GalleryDetailResponse_is_favorited();
                if(parseNode.GetBoolValue() is bool booleanValue)
                {
                    result.Boolean = booleanValue;
                }
                else {
                    result.GalleryDetailResponseIsFavoritedMember1 = new global::Nhentai.Api.Models.GalleryDetailResponse_is_favoritedMember1();
                }
                return result;
            }
            /// <summary>
            /// The deserialization information for the current model
            /// </summary>
            /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
            public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
            {
                if(GalleryDetailResponseIsFavoritedMember1 != null)
                {
                    return ParseNodeHelper.MergeDeserializersForIntersectionWrapper(GalleryDetailResponseIsFavoritedMember1);
                }
                return new Dictionary<string, Action<IParseNode>>();
            }
            /// <summary>
            /// Serializes information the current object
            /// </summary>
            /// <param name="writer">Serialization writer to use to serialize this model</param>
            public virtual void Serialize(ISerializationWriter writer)
            {
                if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
                if(Boolean != null)
                {
                    writer.WriteBoolValue(null, Boolean);
                }
                else {
                    writer.WriteObjectValue<global::Nhentai.Api.Models.GalleryDetailResponse_is_favoritedMember1>(null, GalleryDetailResponseIsFavoritedMember1);
                }
            }
        }
    }
}
#pragma warning restore CS0618
