// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Nhentai.Api.Models
{
    /// <summary>
    /// Response for moderation comment lists.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class ModerationCommentsListResponse : IAdditionalDataHolder, IParsable
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The comments property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Nhentai.Api.Models.ModerationCommentResponse>? Comments { get; set; }
#nullable restore
#else
        public List<global::Nhentai.Api.Models.ModerationCommentResponse> Comments { get; set; }
#endif
        /// <summary>The num_pages property</summary>
        public int? NumPages { get; set; }
        /// <summary>The page property</summary>
        public int? Page { get; set; }
        /// <summary>The per_page property</summary>
        public int? PerPage { get; set; }
        /// <summary>The total property</summary>
        public int? Total { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::Nhentai.Api.Models.ModerationCommentsListResponse"/> and sets the default values.
        /// </summary>
        public ModerationCommentsListResponse()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Nhentai.Api.Models.ModerationCommentsListResponse"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Nhentai.Api.Models.ModerationCommentsListResponse CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Nhentai.Api.Models.ModerationCommentsListResponse();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "comments", n => { Comments = n.GetCollectionOfObjectValues<global::Nhentai.Api.Models.ModerationCommentResponse>(global::Nhentai.Api.Models.ModerationCommentResponse.CreateFromDiscriminatorValue)?.AsList(); } },
                { "num_pages", n => { NumPages = n.GetIntValue(); } },
                { "page", n => { Page = n.GetIntValue(); } },
                { "per_page", n => { PerPage = n.GetIntValue(); } },
                { "total", n => { Total = n.GetIntValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteCollectionOfObjectValues<global::Nhentai.Api.Models.ModerationCommentResponse>("comments", Comments);
            writer.WriteIntValue("num_pages", NumPages);
            writer.WriteIntValue("page", Page);
            writer.WriteIntValue("per_page", PerPage);
            writer.WriteIntValue("total", Total);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
