// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Nhentai.Api.Models
{
    /// <summary>
    /// Comment info for moderation views.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class ModerationCommentResponse : IAdditionalDataHolder, IParsable
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The body property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Body { get; set; }
#nullable restore
#else
        public string Body { get; set; }
#endif
        /// <summary>The gallery_id property</summary>
        public int? GalleryId { get; set; }
        /// <summary>The gallery_title property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Nhentai.Api.Models.ModerationCommentResponse.ModerationCommentResponse_gallery_title? GalleryTitle { get; set; }
#nullable restore
#else
        public global::Nhentai.Api.Models.ModerationCommentResponse.ModerationCommentResponse_gallery_title GalleryTitle { get; set; }
#endif
        /// <summary>The id property</summary>
        public int? Id { get; set; }
        /// <summary>The is_hidden property</summary>
        public bool? IsHidden { get; set; }
        /// <summary>The post_date property</summary>
        public int? PostDate { get; set; }
        /// <summary>The poster_avatar property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? PosterAvatar { get; set; }
#nullable restore
#else
        public string PosterAvatar { get; set; }
#endif
        /// <summary>The poster_id property</summary>
        public int? PosterId { get; set; }
        /// <summary>The poster_is_shadowbanned property</summary>
        public bool? PosterIsShadowbanned { get; set; }
        /// <summary>The poster_slug property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? PosterSlug { get; set; }
#nullable restore
#else
        public string PosterSlug { get; set; }
#endif
        /// <summary>The poster_username property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? PosterUsername { get; set; }
#nullable restore
#else
        public string PosterUsername { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Nhentai.Api.Models.ModerationCommentResponse"/> and sets the default values.
        /// </summary>
        public ModerationCommentResponse()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Nhentai.Api.Models.ModerationCommentResponse"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Nhentai.Api.Models.ModerationCommentResponse CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Nhentai.Api.Models.ModerationCommentResponse();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "body", n => { Body = n.GetStringValue(); } },
                { "gallery_id", n => { GalleryId = n.GetIntValue(); } },
                { "gallery_title", n => { GalleryTitle = n.GetObjectValue<global::Nhentai.Api.Models.ModerationCommentResponse.ModerationCommentResponse_gallery_title>(global::Nhentai.Api.Models.ModerationCommentResponse.ModerationCommentResponse_gallery_title.CreateFromDiscriminatorValue); } },
                { "id", n => { Id = n.GetIntValue(); } },
                { "is_hidden", n => { IsHidden = n.GetBoolValue(); } },
                { "post_date", n => { PostDate = n.GetIntValue(); } },
                { "poster_avatar", n => { PosterAvatar = n.GetStringValue(); } },
                { "poster_id", n => { PosterId = n.GetIntValue(); } },
                { "poster_is_shadowbanned", n => { PosterIsShadowbanned = n.GetBoolValue(); } },
                { "poster_slug", n => { PosterSlug = n.GetStringValue(); } },
                { "poster_username", n => { PosterUsername = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("body", Body);
            writer.WriteIntValue("gallery_id", GalleryId);
            writer.WriteObjectValue<global::Nhentai.Api.Models.ModerationCommentResponse.ModerationCommentResponse_gallery_title>("gallery_title", GalleryTitle);
            writer.WriteIntValue("id", Id);
            writer.WriteBoolValue("is_hidden", IsHidden);
            writer.WriteIntValue("post_date", PostDate);
            writer.WriteStringValue("poster_avatar", PosterAvatar);
            writer.WriteIntValue("poster_id", PosterId);
            writer.WriteBoolValue("poster_is_shadowbanned", PosterIsShadowbanned);
            writer.WriteStringValue("poster_slug", PosterSlug);
            writer.WriteStringValue("poster_username", PosterUsername);
            writer.WriteAdditionalData(AdditionalData);
        }
        /// <summary>
        /// Composed type wrapper for classes <see cref="global::Nhentai.Api.Models.ModerationCommentResponse_gallery_titleMember1"/>, <see cref="string"/>
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class ModerationCommentResponse_gallery_title : IComposedTypeWrapper, IParsable
        {
            /// <summary>Composed type representation for type <see cref="global::Nhentai.Api.Models.ModerationCommentResponse_gallery_titleMember1"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::Nhentai.Api.Models.ModerationCommentResponse_gallery_titleMember1? ModerationCommentResponseGalleryTitleMember1 { get; set; }
#nullable restore
#else
            public global::Nhentai.Api.Models.ModerationCommentResponse_gallery_titleMember1 ModerationCommentResponseGalleryTitleMember1 { get; set; }
#endif
            /// <summary>Composed type representation for type <see cref="string"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public string? String { get; set; }
#nullable restore
#else
            public string String { get; set; }
#endif
            /// <summary>
            /// Creates a new instance of the appropriate class based on discriminator value
            /// </summary>
            /// <returns>A <see cref="global::Nhentai.Api.Models.ModerationCommentResponse.ModerationCommentResponse_gallery_title"/></returns>
            /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
            public static global::Nhentai.Api.Models.ModerationCommentResponse.ModerationCommentResponse_gallery_title CreateFromDiscriminatorValue(IParseNode parseNode)
            {
                if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
                var result = new global::Nhentai.Api.Models.ModerationCommentResponse.ModerationCommentResponse_gallery_title();
                if(parseNode.GetStringValue() is string stringValue)
                {
                    result.String = stringValue;
                }
                else {
                    result.ModerationCommentResponseGalleryTitleMember1 = new global::Nhentai.Api.Models.ModerationCommentResponse_gallery_titleMember1();
                }
                return result;
            }
            /// <summary>
            /// The deserialization information for the current model
            /// </summary>
            /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
            public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
            {
                if(ModerationCommentResponseGalleryTitleMember1 != null)
                {
                    return ParseNodeHelper.MergeDeserializersForIntersectionWrapper(ModerationCommentResponseGalleryTitleMember1);
                }
                return new Dictionary<string, Action<IParseNode>>();
            }
            /// <summary>
            /// Serializes information the current object
            /// </summary>
            /// <param name="writer">Serialization writer to use to serialize this model</param>
            public virtual void Serialize(ISerializationWriter writer)
            {
                if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
                if(String != null)
                {
                    writer.WriteStringValue(null, String);
                }
                else {
                    writer.WriteObjectValue<global::Nhentai.Api.Models.ModerationCommentResponse_gallery_titleMember1>(null, ModerationCommentResponseGalleryTitleMember1);
                }
            }
        }
    }
}
#pragma warning restore CS0618
