// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Nhentai.Api.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class SessionListItem : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The created_at property</summary>
        public int? CreatedAt { get; set; }
        /// <summary>The current property</summary>
        public bool? Current { get; set; }
        /// <summary>The expires_at property</summary>
        public int? ExpiresAt { get; set; }
        /// <summary>The id property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Id { get; set; }
#nullable restore
#else
        public string Id { get; set; }
#endif
        /// <summary>The ip_address property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Nhentai.Api.Models.SessionListItem.SessionListItem_ip_address? IpAddress { get; set; }
#nullable restore
#else
        public global::Nhentai.Api.Models.SessionListItem.SessionListItem_ip_address IpAddress { get; set; }
#endif
        /// <summary>The user_agent property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Nhentai.Api.Models.SessionListItem.SessionListItem_user_agent? UserAgent { get; set; }
#nullable restore
#else
        public global::Nhentai.Api.Models.SessionListItem.SessionListItem_user_agent UserAgent { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Nhentai.Api.Models.SessionListItem"/> and sets the default values.
        /// </summary>
        public SessionListItem()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Nhentai.Api.Models.SessionListItem"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Nhentai.Api.Models.SessionListItem CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Nhentai.Api.Models.SessionListItem();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "created_at", n => { CreatedAt = n.GetIntValue(); } },
                { "current", n => { Current = n.GetBoolValue(); } },
                { "expires_at", n => { ExpiresAt = n.GetIntValue(); } },
                { "id", n => { Id = n.GetStringValue(); } },
                { "ip_address", n => { IpAddress = n.GetObjectValue<global::Nhentai.Api.Models.SessionListItem.SessionListItem_ip_address>(global::Nhentai.Api.Models.SessionListItem.SessionListItem_ip_address.CreateFromDiscriminatorValue); } },
                { "user_agent", n => { UserAgent = n.GetObjectValue<global::Nhentai.Api.Models.SessionListItem.SessionListItem_user_agent>(global::Nhentai.Api.Models.SessionListItem.SessionListItem_user_agent.CreateFromDiscriminatorValue); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteIntValue("created_at", CreatedAt);
            writer.WriteBoolValue("current", Current);
            writer.WriteIntValue("expires_at", ExpiresAt);
            writer.WriteStringValue("id", Id);
            writer.WriteObjectValue<global::Nhentai.Api.Models.SessionListItem.SessionListItem_ip_address>("ip_address", IpAddress);
            writer.WriteObjectValue<global::Nhentai.Api.Models.SessionListItem.SessionListItem_user_agent>("user_agent", UserAgent);
            writer.WriteAdditionalData(AdditionalData);
        }
        /// <summary>
        /// Composed type wrapper for classes <see cref="global::Nhentai.Api.Models.SessionListItem_ip_addressMember1"/>, <see cref="string"/>
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class SessionListItem_ip_address : IComposedTypeWrapper, IParsable
        {
            /// <summary>Composed type representation for type <see cref="global::Nhentai.Api.Models.SessionListItem_ip_addressMember1"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::Nhentai.Api.Models.SessionListItem_ip_addressMember1? SessionListItemIpAddressMember1 { get; set; }
#nullable restore
#else
            public global::Nhentai.Api.Models.SessionListItem_ip_addressMember1 SessionListItemIpAddressMember1 { get; set; }
#endif
            /// <summary>Composed type representation for type <see cref="string"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public string? String { get; set; }
#nullable restore
#else
            public string String { get; set; }
#endif
            /// <summary>
            /// Creates a new instance of the appropriate class based on discriminator value
            /// </summary>
            /// <returns>A <see cref="global::Nhentai.Api.Models.SessionListItem.SessionListItem_ip_address"/></returns>
            /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
            public static global::Nhentai.Api.Models.SessionListItem.SessionListItem_ip_address CreateFromDiscriminatorValue(IParseNode parseNode)
            {
                if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
                var result = new global::Nhentai.Api.Models.SessionListItem.SessionListItem_ip_address();
                if(parseNode.GetStringValue() is string stringValue)
                {
                    result.String = stringValue;
                }
                else {
                    result.SessionListItemIpAddressMember1 = new global::Nhentai.Api.Models.SessionListItem_ip_addressMember1();
                }
                return result;
            }
            /// <summary>
            /// The deserialization information for the current model
            /// </summary>
            /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
            public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
            {
                if(SessionListItemIpAddressMember1 != null)
                {
                    return ParseNodeHelper.MergeDeserializersForIntersectionWrapper(SessionListItemIpAddressMember1);
                }
                return new Dictionary<string, Action<IParseNode>>();
            }
            /// <summary>
            /// Serializes information the current object
            /// </summary>
            /// <param name="writer">Serialization writer to use to serialize this model</param>
            public virtual void Serialize(ISerializationWriter writer)
            {
                if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
                if(String != null)
                {
                    writer.WriteStringValue(null, String);
                }
                else {
                    writer.WriteObjectValue<global::Nhentai.Api.Models.SessionListItem_ip_addressMember1>(null, SessionListItemIpAddressMember1);
                }
            }
        }
        /// <summary>
        /// Composed type wrapper for classes <see cref="global::Nhentai.Api.Models.SessionListItem_user_agentMember1"/>, <see cref="string"/>
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class SessionListItem_user_agent : IComposedTypeWrapper, IParsable
        {
            /// <summary>Composed type representation for type <see cref="global::Nhentai.Api.Models.SessionListItem_user_agentMember1"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::Nhentai.Api.Models.SessionListItem_user_agentMember1? SessionListItemUserAgentMember1 { get; set; }
#nullable restore
#else
            public global::Nhentai.Api.Models.SessionListItem_user_agentMember1 SessionListItemUserAgentMember1 { get; set; }
#endif
            /// <summary>Composed type representation for type <see cref="string"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public string? String { get; set; }
#nullable restore
#else
            public string String { get; set; }
#endif
            /// <summary>
            /// Creates a new instance of the appropriate class based on discriminator value
            /// </summary>
            /// <returns>A <see cref="global::Nhentai.Api.Models.SessionListItem.SessionListItem_user_agent"/></returns>
            /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
            public static global::Nhentai.Api.Models.SessionListItem.SessionListItem_user_agent CreateFromDiscriminatorValue(IParseNode parseNode)
            {
                if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
                var result = new global::Nhentai.Api.Models.SessionListItem.SessionListItem_user_agent();
                if(parseNode.GetStringValue() is string stringValue)
                {
                    result.String = stringValue;
                }
                else {
                    result.SessionListItemUserAgentMember1 = new global::Nhentai.Api.Models.SessionListItem_user_agentMember1();
                }
                return result;
            }
            /// <summary>
            /// The deserialization information for the current model
            /// </summary>
            /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
            public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
            {
                if(SessionListItemUserAgentMember1 != null)
                {
                    return ParseNodeHelper.MergeDeserializersForIntersectionWrapper(SessionListItemUserAgentMember1);
                }
                return new Dictionary<string, Action<IParseNode>>();
            }
            /// <summary>
            /// Serializes information the current object
            /// </summary>
            /// <param name="writer">Serialization writer to use to serialize this model</param>
            public virtual void Serialize(ISerializationWriter writer)
            {
                if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
                if(String != null)
                {
                    writer.WriteStringValue(null, String);
                }
                else {
                    writer.WriteObjectValue<global::Nhentai.Api.Models.SessionListItem_user_agentMember1>(null, SessionListItemUserAgentMember1);
                }
            }
        }
    }
}
#pragma warning restore CS0618
