// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Nhentai.Api.Models
{
    /// <summary>
    /// Request body for updating user profile.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class UpdateProfileRequest : IAdditionalDataHolder, IParsable
    {
        /// <summary>The about property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Nhentai.Api.Models.UpdateProfileRequest.UpdateProfileRequest_about? About { get; set; }
#nullable restore
#else
        public global::Nhentai.Api.Models.UpdateProfileRequest.UpdateProfileRequest_about About { get; set; }
#endif
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The current_password property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Nhentai.Api.Models.UpdateProfileRequest.UpdateProfileRequest_current_password? CurrentPassword { get; set; }
#nullable restore
#else
        public global::Nhentai.Api.Models.UpdateProfileRequest.UpdateProfileRequest_current_password CurrentPassword { get; set; }
#endif
        /// <summary>The email property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Nhentai.Api.Models.UpdateProfileRequest.UpdateProfileRequest_email? Email { get; set; }
#nullable restore
#else
        public global::Nhentai.Api.Models.UpdateProfileRequest.UpdateProfileRequest_email Email { get; set; }
#endif
        /// <summary>The favorite_tags property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Nhentai.Api.Models.UpdateProfileRequest.UpdateProfileRequest_favorite_tags? FavoriteTags { get; set; }
#nullable restore
#else
        public global::Nhentai.Api.Models.UpdateProfileRequest.UpdateProfileRequest_favorite_tags FavoriteTags { get; set; }
#endif
        /// <summary>The new_password property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Nhentai.Api.Models.UpdateProfileRequest.UpdateProfileRequest_new_password? NewPassword { get; set; }
#nullable restore
#else
        public global::Nhentai.Api.Models.UpdateProfileRequest.UpdateProfileRequest_new_password NewPassword { get; set; }
#endif
        /// <summary>The remove_avatar property</summary>
        public bool? RemoveAvatar { get; set; }
        /// <summary>The theme property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Nhentai.Api.Models.UpdateProfileRequest.UpdateProfileRequest_theme? Theme { get; set; }
#nullable restore
#else
        public global::Nhentai.Api.Models.UpdateProfileRequest.UpdateProfileRequest_theme Theme { get; set; }
#endif
        /// <summary>The username property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Nhentai.Api.Models.UpdateProfileRequest.UpdateProfileRequest_username? Username { get; set; }
#nullable restore
#else
        public global::Nhentai.Api.Models.UpdateProfileRequest.UpdateProfileRequest_username Username { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Nhentai.Api.Models.UpdateProfileRequest"/> and sets the default values.
        /// </summary>
        public UpdateProfileRequest()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Nhentai.Api.Models.UpdateProfileRequest"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Nhentai.Api.Models.UpdateProfileRequest CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Nhentai.Api.Models.UpdateProfileRequest();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "about", n => { About = n.GetObjectValue<global::Nhentai.Api.Models.UpdateProfileRequest.UpdateProfileRequest_about>(global::Nhentai.Api.Models.UpdateProfileRequest.UpdateProfileRequest_about.CreateFromDiscriminatorValue); } },
                { "current_password", n => { CurrentPassword = n.GetObjectValue<global::Nhentai.Api.Models.UpdateProfileRequest.UpdateProfileRequest_current_password>(global::Nhentai.Api.Models.UpdateProfileRequest.UpdateProfileRequest_current_password.CreateFromDiscriminatorValue); } },
                { "email", n => { Email = n.GetObjectValue<global::Nhentai.Api.Models.UpdateProfileRequest.UpdateProfileRequest_email>(global::Nhentai.Api.Models.UpdateProfileRequest.UpdateProfileRequest_email.CreateFromDiscriminatorValue); } },
                { "favorite_tags", n => { FavoriteTags = n.GetObjectValue<global::Nhentai.Api.Models.UpdateProfileRequest.UpdateProfileRequest_favorite_tags>(global::Nhentai.Api.Models.UpdateProfileRequest.UpdateProfileRequest_favorite_tags.CreateFromDiscriminatorValue); } },
                { "new_password", n => { NewPassword = n.GetObjectValue<global::Nhentai.Api.Models.UpdateProfileRequest.UpdateProfileRequest_new_password>(global::Nhentai.Api.Models.UpdateProfileRequest.UpdateProfileRequest_new_password.CreateFromDiscriminatorValue); } },
                { "remove_avatar", n => { RemoveAvatar = n.GetBoolValue(); } },
                { "theme", n => { Theme = n.GetObjectValue<global::Nhentai.Api.Models.UpdateProfileRequest.UpdateProfileRequest_theme>(global::Nhentai.Api.Models.UpdateProfileRequest.UpdateProfileRequest_theme.CreateFromDiscriminatorValue); } },
                { "username", n => { Username = n.GetObjectValue<global::Nhentai.Api.Models.UpdateProfileRequest.UpdateProfileRequest_username>(global::Nhentai.Api.Models.UpdateProfileRequest.UpdateProfileRequest_username.CreateFromDiscriminatorValue); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteObjectValue<global::Nhentai.Api.Models.UpdateProfileRequest.UpdateProfileRequest_about>("about", About);
            writer.WriteObjectValue<global::Nhentai.Api.Models.UpdateProfileRequest.UpdateProfileRequest_current_password>("current_password", CurrentPassword);
            writer.WriteObjectValue<global::Nhentai.Api.Models.UpdateProfileRequest.UpdateProfileRequest_email>("email", Email);
            writer.WriteObjectValue<global::Nhentai.Api.Models.UpdateProfileRequest.UpdateProfileRequest_favorite_tags>("favorite_tags", FavoriteTags);
            writer.WriteObjectValue<global::Nhentai.Api.Models.UpdateProfileRequest.UpdateProfileRequest_new_password>("new_password", NewPassword);
            writer.WriteBoolValue("remove_avatar", RemoveAvatar);
            writer.WriteObjectValue<global::Nhentai.Api.Models.UpdateProfileRequest.UpdateProfileRequest_theme>("theme", Theme);
            writer.WriteObjectValue<global::Nhentai.Api.Models.UpdateProfileRequest.UpdateProfileRequest_username>("username", Username);
            writer.WriteAdditionalData(AdditionalData);
        }
        /// <summary>
        /// Composed type wrapper for classes <see cref="global::Nhentai.Api.Models.UpdateProfileRequest_aboutMember1"/>, <see cref="string"/>
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class UpdateProfileRequest_about : IComposedTypeWrapper, IParsable
        {
            /// <summary>Composed type representation for type <see cref="string"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public string? String { get; set; }
#nullable restore
#else
            public string String { get; set; }
#endif
            /// <summary>Composed type representation for type <see cref="global::Nhentai.Api.Models.UpdateProfileRequest_aboutMember1"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::Nhentai.Api.Models.UpdateProfileRequest_aboutMember1? UpdateProfileRequestAboutMember1 { get; set; }
#nullable restore
#else
            public global::Nhentai.Api.Models.UpdateProfileRequest_aboutMember1 UpdateProfileRequestAboutMember1 { get; set; }
#endif
            /// <summary>
            /// Creates a new instance of the appropriate class based on discriminator value
            /// </summary>
            /// <returns>A <see cref="global::Nhentai.Api.Models.UpdateProfileRequest.UpdateProfileRequest_about"/></returns>
            /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
            public static global::Nhentai.Api.Models.UpdateProfileRequest.UpdateProfileRequest_about CreateFromDiscriminatorValue(IParseNode parseNode)
            {
                if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
                var result = new global::Nhentai.Api.Models.UpdateProfileRequest.UpdateProfileRequest_about();
                if(parseNode.GetStringValue() is string stringValue)
                {
                    result.String = stringValue;
                }
                else {
                    result.UpdateProfileRequestAboutMember1 = new global::Nhentai.Api.Models.UpdateProfileRequest_aboutMember1();
                }
                return result;
            }
            /// <summary>
            /// The deserialization information for the current model
            /// </summary>
            /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
            public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
            {
                if(UpdateProfileRequestAboutMember1 != null)
                {
                    return ParseNodeHelper.MergeDeserializersForIntersectionWrapper(UpdateProfileRequestAboutMember1);
                }
                return new Dictionary<string, Action<IParseNode>>();
            }
            /// <summary>
            /// Serializes information the current object
            /// </summary>
            /// <param name="writer">Serialization writer to use to serialize this model</param>
            public virtual void Serialize(ISerializationWriter writer)
            {
                if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
                if(String != null)
                {
                    writer.WriteStringValue(null, String);
                }
                else {
                    writer.WriteObjectValue<global::Nhentai.Api.Models.UpdateProfileRequest_aboutMember1>(null, UpdateProfileRequestAboutMember1);
                }
            }
        }
        /// <summary>
        /// Composed type wrapper for classes <see cref="global::Nhentai.Api.Models.UpdateProfileRequest_current_passwordMember1"/>, <see cref="string"/>
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class UpdateProfileRequest_current_password : IComposedTypeWrapper, IParsable
        {
            /// <summary>Composed type representation for type <see cref="string"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public string? String { get; set; }
#nullable restore
#else
            public string String { get; set; }
#endif
            /// <summary>Composed type representation for type <see cref="global::Nhentai.Api.Models.UpdateProfileRequest_current_passwordMember1"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::Nhentai.Api.Models.UpdateProfileRequest_current_passwordMember1? UpdateProfileRequestCurrentPasswordMember1 { get; set; }
#nullable restore
#else
            public global::Nhentai.Api.Models.UpdateProfileRequest_current_passwordMember1 UpdateProfileRequestCurrentPasswordMember1 { get; set; }
#endif
            /// <summary>
            /// Creates a new instance of the appropriate class based on discriminator value
            /// </summary>
            /// <returns>A <see cref="global::Nhentai.Api.Models.UpdateProfileRequest.UpdateProfileRequest_current_password"/></returns>
            /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
            public static global::Nhentai.Api.Models.UpdateProfileRequest.UpdateProfileRequest_current_password CreateFromDiscriminatorValue(IParseNode parseNode)
            {
                if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
                var result = new global::Nhentai.Api.Models.UpdateProfileRequest.UpdateProfileRequest_current_password();
                if(parseNode.GetStringValue() is string stringValue)
                {
                    result.String = stringValue;
                }
                else {
                    result.UpdateProfileRequestCurrentPasswordMember1 = new global::Nhentai.Api.Models.UpdateProfileRequest_current_passwordMember1();
                }
                return result;
            }
            /// <summary>
            /// The deserialization information for the current model
            /// </summary>
            /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
            public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
            {
                if(UpdateProfileRequestCurrentPasswordMember1 != null)
                {
                    return ParseNodeHelper.MergeDeserializersForIntersectionWrapper(UpdateProfileRequestCurrentPasswordMember1);
                }
                return new Dictionary<string, Action<IParseNode>>();
            }
            /// <summary>
            /// Serializes information the current object
            /// </summary>
            /// <param name="writer">Serialization writer to use to serialize this model</param>
            public virtual void Serialize(ISerializationWriter writer)
            {
                if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
                if(String != null)
                {
                    writer.WriteStringValue(null, String);
                }
                else {
                    writer.WriteObjectValue<global::Nhentai.Api.Models.UpdateProfileRequest_current_passwordMember1>(null, UpdateProfileRequestCurrentPasswordMember1);
                }
            }
        }
        /// <summary>
        /// Composed type wrapper for classes <see cref="global::Nhentai.Api.Models.UpdateProfileRequest_emailMember1"/>, <see cref="string"/>
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class UpdateProfileRequest_email : IComposedTypeWrapper, IParsable
        {
            /// <summary>Composed type representation for type <see cref="string"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public string? String { get; set; }
#nullable restore
#else
            public string String { get; set; }
#endif
            /// <summary>Composed type representation for type <see cref="global::Nhentai.Api.Models.UpdateProfileRequest_emailMember1"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::Nhentai.Api.Models.UpdateProfileRequest_emailMember1? UpdateProfileRequestEmailMember1 { get; set; }
#nullable restore
#else
            public global::Nhentai.Api.Models.UpdateProfileRequest_emailMember1 UpdateProfileRequestEmailMember1 { get; set; }
#endif
            /// <summary>
            /// Creates a new instance of the appropriate class based on discriminator value
            /// </summary>
            /// <returns>A <see cref="global::Nhentai.Api.Models.UpdateProfileRequest.UpdateProfileRequest_email"/></returns>
            /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
            public static global::Nhentai.Api.Models.UpdateProfileRequest.UpdateProfileRequest_email CreateFromDiscriminatorValue(IParseNode parseNode)
            {
                if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
                var result = new global::Nhentai.Api.Models.UpdateProfileRequest.UpdateProfileRequest_email();
                if(parseNode.GetStringValue() is string stringValue)
                {
                    result.String = stringValue;
                }
                else {
                    result.UpdateProfileRequestEmailMember1 = new global::Nhentai.Api.Models.UpdateProfileRequest_emailMember1();
                }
                return result;
            }
            /// <summary>
            /// The deserialization information for the current model
            /// </summary>
            /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
            public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
            {
                if(UpdateProfileRequestEmailMember1 != null)
                {
                    return ParseNodeHelper.MergeDeserializersForIntersectionWrapper(UpdateProfileRequestEmailMember1);
                }
                return new Dictionary<string, Action<IParseNode>>();
            }
            /// <summary>
            /// Serializes information the current object
            /// </summary>
            /// <param name="writer">Serialization writer to use to serialize this model</param>
            public virtual void Serialize(ISerializationWriter writer)
            {
                if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
                if(String != null)
                {
                    writer.WriteStringValue(null, String);
                }
                else {
                    writer.WriteObjectValue<global::Nhentai.Api.Models.UpdateProfileRequest_emailMember1>(null, UpdateProfileRequestEmailMember1);
                }
            }
        }
        /// <summary>
        /// Composed type wrapper for classes <see cref="global::Nhentai.Api.Models.UpdateProfileRequest_favorite_tagsMember1"/>, <see cref="string"/>
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class UpdateProfileRequest_favorite_tags : IComposedTypeWrapper, IParsable
        {
            /// <summary>Composed type representation for type <see cref="string"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public string? String { get; set; }
#nullable restore
#else
            public string String { get; set; }
#endif
            /// <summary>Composed type representation for type <see cref="global::Nhentai.Api.Models.UpdateProfileRequest_favorite_tagsMember1"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::Nhentai.Api.Models.UpdateProfileRequest_favorite_tagsMember1? UpdateProfileRequestFavoriteTagsMember1 { get; set; }
#nullable restore
#else
            public global::Nhentai.Api.Models.UpdateProfileRequest_favorite_tagsMember1 UpdateProfileRequestFavoriteTagsMember1 { get; set; }
#endif
            /// <summary>
            /// Creates a new instance of the appropriate class based on discriminator value
            /// </summary>
            /// <returns>A <see cref="global::Nhentai.Api.Models.UpdateProfileRequest.UpdateProfileRequest_favorite_tags"/></returns>
            /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
            public static global::Nhentai.Api.Models.UpdateProfileRequest.UpdateProfileRequest_favorite_tags CreateFromDiscriminatorValue(IParseNode parseNode)
            {
                if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
                var result = new global::Nhentai.Api.Models.UpdateProfileRequest.UpdateProfileRequest_favorite_tags();
                if(parseNode.GetStringValue() is string stringValue)
                {
                    result.String = stringValue;
                }
                else {
                    result.UpdateProfileRequestFavoriteTagsMember1 = new global::Nhentai.Api.Models.UpdateProfileRequest_favorite_tagsMember1();
                }
                return result;
            }
            /// <summary>
            /// The deserialization information for the current model
            /// </summary>
            /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
            public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
            {
                if(UpdateProfileRequestFavoriteTagsMember1 != null)
                {
                    return ParseNodeHelper.MergeDeserializersForIntersectionWrapper(UpdateProfileRequestFavoriteTagsMember1);
                }
                return new Dictionary<string, Action<IParseNode>>();
            }
            /// <summary>
            /// Serializes information the current object
            /// </summary>
            /// <param name="writer">Serialization writer to use to serialize this model</param>
            public virtual void Serialize(ISerializationWriter writer)
            {
                if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
                if(String != null)
                {
                    writer.WriteStringValue(null, String);
                }
                else {
                    writer.WriteObjectValue<global::Nhentai.Api.Models.UpdateProfileRequest_favorite_tagsMember1>(null, UpdateProfileRequestFavoriteTagsMember1);
                }
            }
        }
        /// <summary>
        /// Composed type wrapper for classes <see cref="global::Nhentai.Api.Models.UpdateProfileRequest_new_passwordMember1"/>, <see cref="string"/>
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class UpdateProfileRequest_new_password : IComposedTypeWrapper, IParsable
        {
            /// <summary>Composed type representation for type <see cref="string"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public string? String { get; set; }
#nullable restore
#else
            public string String { get; set; }
#endif
            /// <summary>Composed type representation for type <see cref="global::Nhentai.Api.Models.UpdateProfileRequest_new_passwordMember1"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::Nhentai.Api.Models.UpdateProfileRequest_new_passwordMember1? UpdateProfileRequestNewPasswordMember1 { get; set; }
#nullable restore
#else
            public global::Nhentai.Api.Models.UpdateProfileRequest_new_passwordMember1 UpdateProfileRequestNewPasswordMember1 { get; set; }
#endif
            /// <summary>
            /// Creates a new instance of the appropriate class based on discriminator value
            /// </summary>
            /// <returns>A <see cref="global::Nhentai.Api.Models.UpdateProfileRequest.UpdateProfileRequest_new_password"/></returns>
            /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
            public static global::Nhentai.Api.Models.UpdateProfileRequest.UpdateProfileRequest_new_password CreateFromDiscriminatorValue(IParseNode parseNode)
            {
                if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
                var result = new global::Nhentai.Api.Models.UpdateProfileRequest.UpdateProfileRequest_new_password();
                if(parseNode.GetStringValue() is string stringValue)
                {
                    result.String = stringValue;
                }
                else {
                    result.UpdateProfileRequestNewPasswordMember1 = new global::Nhentai.Api.Models.UpdateProfileRequest_new_passwordMember1();
                }
                return result;
            }
            /// <summary>
            /// The deserialization information for the current model
            /// </summary>
            /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
            public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
            {
                if(UpdateProfileRequestNewPasswordMember1 != null)
                {
                    return ParseNodeHelper.MergeDeserializersForIntersectionWrapper(UpdateProfileRequestNewPasswordMember1);
                }
                return new Dictionary<string, Action<IParseNode>>();
            }
            /// <summary>
            /// Serializes information the current object
            /// </summary>
            /// <param name="writer">Serialization writer to use to serialize this model</param>
            public virtual void Serialize(ISerializationWriter writer)
            {
                if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
                if(String != null)
                {
                    writer.WriteStringValue(null, String);
                }
                else {
                    writer.WriteObjectValue<global::Nhentai.Api.Models.UpdateProfileRequest_new_passwordMember1>(null, UpdateProfileRequestNewPasswordMember1);
                }
            }
        }
        /// <summary>
        /// Composed type wrapper for classes <see cref="global::Nhentai.Api.Models.UpdateProfileRequest_themeMember1"/>, <see cref="string"/>
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class UpdateProfileRequest_theme : IComposedTypeWrapper, IParsable
        {
            /// <summary>Composed type representation for type <see cref="string"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public string? String { get; set; }
#nullable restore
#else
            public string String { get; set; }
#endif
            /// <summary>Composed type representation for type <see cref="global::Nhentai.Api.Models.UpdateProfileRequest_themeMember1"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::Nhentai.Api.Models.UpdateProfileRequest_themeMember1? UpdateProfileRequestThemeMember1 { get; set; }
#nullable restore
#else
            public global::Nhentai.Api.Models.UpdateProfileRequest_themeMember1 UpdateProfileRequestThemeMember1 { get; set; }
#endif
            /// <summary>
            /// Creates a new instance of the appropriate class based on discriminator value
            /// </summary>
            /// <returns>A <see cref="global::Nhentai.Api.Models.UpdateProfileRequest.UpdateProfileRequest_theme"/></returns>
            /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
            public static global::Nhentai.Api.Models.UpdateProfileRequest.UpdateProfileRequest_theme CreateFromDiscriminatorValue(IParseNode parseNode)
            {
                if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
                var result = new global::Nhentai.Api.Models.UpdateProfileRequest.UpdateProfileRequest_theme();
                if(parseNode.GetStringValue() is string stringValue)
                {
                    result.String = stringValue;
                }
                else {
                    result.UpdateProfileRequestThemeMember1 = new global::Nhentai.Api.Models.UpdateProfileRequest_themeMember1();
                }
                return result;
            }
            /// <summary>
            /// The deserialization information for the current model
            /// </summary>
            /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
            public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
            {
                if(UpdateProfileRequestThemeMember1 != null)
                {
                    return ParseNodeHelper.MergeDeserializersForIntersectionWrapper(UpdateProfileRequestThemeMember1);
                }
                return new Dictionary<string, Action<IParseNode>>();
            }
            /// <summary>
            /// Serializes information the current object
            /// </summary>
            /// <param name="writer">Serialization writer to use to serialize this model</param>
            public virtual void Serialize(ISerializationWriter writer)
            {
                if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
                if(String != null)
                {
                    writer.WriteStringValue(null, String);
                }
                else {
                    writer.WriteObjectValue<global::Nhentai.Api.Models.UpdateProfileRequest_themeMember1>(null, UpdateProfileRequestThemeMember1);
                }
            }
        }
        /// <summary>
        /// Composed type wrapper for classes <see cref="global::Nhentai.Api.Models.UpdateProfileRequest_usernameMember1"/>, <see cref="string"/>
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class UpdateProfileRequest_username : IComposedTypeWrapper, IParsable
        {
            /// <summary>Composed type representation for type <see cref="string"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public string? String { get; set; }
#nullable restore
#else
            public string String { get; set; }
#endif
            /// <summary>Composed type representation for type <see cref="global::Nhentai.Api.Models.UpdateProfileRequest_usernameMember1"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::Nhentai.Api.Models.UpdateProfileRequest_usernameMember1? UpdateProfileRequestUsernameMember1 { get; set; }
#nullable restore
#else
            public global::Nhentai.Api.Models.UpdateProfileRequest_usernameMember1 UpdateProfileRequestUsernameMember1 { get; set; }
#endif
            /// <summary>
            /// Creates a new instance of the appropriate class based on discriminator value
            /// </summary>
            /// <returns>A <see cref="global::Nhentai.Api.Models.UpdateProfileRequest.UpdateProfileRequest_username"/></returns>
            /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
            public static global::Nhentai.Api.Models.UpdateProfileRequest.UpdateProfileRequest_username CreateFromDiscriminatorValue(IParseNode parseNode)
            {
                if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
                var result = new global::Nhentai.Api.Models.UpdateProfileRequest.UpdateProfileRequest_username();
                if(parseNode.GetStringValue() is string stringValue)
                {
                    result.String = stringValue;
                }
                else {
                    result.UpdateProfileRequestUsernameMember1 = new global::Nhentai.Api.Models.UpdateProfileRequest_usernameMember1();
                }
                return result;
            }
            /// <summary>
            /// The deserialization information for the current model
            /// </summary>
            /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
            public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
            {
                if(UpdateProfileRequestUsernameMember1 != null)
                {
                    return ParseNodeHelper.MergeDeserializersForIntersectionWrapper(UpdateProfileRequestUsernameMember1);
                }
                return new Dictionary<string, Action<IParseNode>>();
            }
            /// <summary>
            /// Serializes information the current object
            /// </summary>
            /// <param name="writer">Serialization writer to use to serialize this model</param>
            public virtual void Serialize(ISerializationWriter writer)
            {
                if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
                if(String != null)
                {
                    writer.WriteStringValue(null, String);
                }
                else {
                    writer.WriteObjectValue<global::Nhentai.Api.Models.UpdateProfileRequest_usernameMember1>(null, UpdateProfileRequestUsernameMember1);
                }
            }
        }
    }
}
#pragma warning restore CS0618
