// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Nhentai.Api.Models
{
    /// <summary>
    /// Full user profile response.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class UserProfileResponse : IAdditionalDataHolder, IParsable
    {
        /// <summary>The about property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? About { get; set; }
#nullable restore
#else
        public string About { get; set; }
#endif
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The avatar_url property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? AvatarUrl { get; set; }
#nullable restore
#else
        public string AvatarUrl { get; set; }
#endif
        /// <summary>The date_joined property</summary>
        public int? DateJoined { get; set; }
        /// <summary>The favorite_tags property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? FavoriteTags { get; set; }
#nullable restore
#else
        public string FavoriteTags { get; set; }
#endif
        /// <summary>The id property</summary>
        public int? Id { get; set; }
        /// <summary>The is_staff property</summary>
        public bool? IsStaff { get; set; }
        /// <summary>The is_superuser property</summary>
        public bool? IsSuperuser { get; set; }
        /// <summary>The recent_comments property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Nhentai.Api.Models.RecentComment>? RecentComments { get; set; }
#nullable restore
#else
        public List<global::Nhentai.Api.Models.RecentComment> RecentComments { get; set; }
#endif
        /// <summary>The recent_favorites property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Nhentai.Api.Models.RecentFavorite>? RecentFavorites { get; set; }
#nullable restore
#else
        public List<global::Nhentai.Api.Models.RecentFavorite> RecentFavorites { get; set; }
#endif
        /// <summary>The slug property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Slug { get; set; }
#nullable restore
#else
        public string Slug { get; set; }
#endif
        /// <summary>The username property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Username { get; set; }
#nullable restore
#else
        public string Username { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Nhentai.Api.Models.UserProfileResponse"/> and sets the default values.
        /// </summary>
        public UserProfileResponse()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Nhentai.Api.Models.UserProfileResponse"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Nhentai.Api.Models.UserProfileResponse CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Nhentai.Api.Models.UserProfileResponse();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "about", n => { About = n.GetStringValue(); } },
                { "avatar_url", n => { AvatarUrl = n.GetStringValue(); } },
                { "date_joined", n => { DateJoined = n.GetIntValue(); } },
                { "favorite_tags", n => { FavoriteTags = n.GetStringValue(); } },
                { "id", n => { Id = n.GetIntValue(); } },
                { "is_staff", n => { IsStaff = n.GetBoolValue(); } },
                { "is_superuser", n => { IsSuperuser = n.GetBoolValue(); } },
                { "recent_comments", n => { RecentComments = n.GetCollectionOfObjectValues<global::Nhentai.Api.Models.RecentComment>(global::Nhentai.Api.Models.RecentComment.CreateFromDiscriminatorValue)?.AsList(); } },
                { "recent_favorites", n => { RecentFavorites = n.GetCollectionOfObjectValues<global::Nhentai.Api.Models.RecentFavorite>(global::Nhentai.Api.Models.RecentFavorite.CreateFromDiscriminatorValue)?.AsList(); } },
                { "slug", n => { Slug = n.GetStringValue(); } },
                { "username", n => { Username = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("about", About);
            writer.WriteStringValue("avatar_url", AvatarUrl);
            writer.WriteIntValue("date_joined", DateJoined);
            writer.WriteStringValue("favorite_tags", FavoriteTags);
            writer.WriteIntValue("id", Id);
            writer.WriteBoolValue("is_staff", IsStaff);
            writer.WriteBoolValue("is_superuser", IsSuperuser);
            writer.WriteCollectionOfObjectValues<global::Nhentai.Api.Models.RecentComment>("recent_comments", RecentComments);
            writer.WriteCollectionOfObjectValues<global::Nhentai.Api.Models.RecentFavorite>("recent_favorites", RecentFavorites);
            writer.WriteStringValue("slug", Slug);
            writer.WriteStringValue("username", Username);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
