// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using Nhentai.Api.Api.V2.Blacklist.Ids;
using Nhentai.Api.Models;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace Nhentai.Api.Api.V2.Blacklist
{
    /// <summary>
    /// Builds and executes requests for operations under \api\v2\blacklist
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class BlacklistRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The ids property</summary>
        public global::Nhentai.Api.Api.V2.Blacklist.Ids.IdsRequestBuilder Ids
        {
            get => new global::Nhentai.Api.Api.V2.Blacklist.Ids.IdsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Nhentai.Api.Api.V2.Blacklist.BlacklistRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public BlacklistRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/v2/blacklist", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Nhentai.Api.Api.V2.Blacklist.BlacklistRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public BlacklistRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/v2/blacklist", rawUrl)
        {
        }
        /// <summary>
        /// Get the authenticated user&apos;s blacklisted tags.---**Auth:** User Token or API Key**Rate limits:**- 15/1min per user- 15/1min per API key owner
        /// </summary>
        /// <returns>A <see cref="global::Nhentai.Api.Models.BlacklistListResponse"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::Nhentai.Api.Models.ErrorResponse">When receiving a 401 status code</exception>
        /// <exception cref="global::Nhentai.Api.Models.ErrorResponse">When receiving a 429 status code</exception>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::Nhentai.Api.Models.BlacklistListResponse?> GetAsync(Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::Nhentai.Api.Models.BlacklistListResponse> GetAsync(Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToGetRequestInformation(requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "401", global::Nhentai.Api.Models.ErrorResponse.CreateFromDiscriminatorValue },
                { "429", global::Nhentai.Api.Models.ErrorResponse.CreateFromDiscriminatorValue },
            };
            return await RequestAdapter.SendAsync<global::Nhentai.Api.Models.BlacklistListResponse>(requestInfo, global::Nhentai.Api.Models.BlacklistListResponse.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Add or remove tags from the authenticated user&apos;s blacklist.---**Auth:** User Token or API Key**Rate limits:**- 20/15min per user- 20/15min per API key owner
        /// </summary>
        /// <returns>A <see cref="global::Nhentai.Api.Models.BlacklistResponse"/></returns>
        /// <param name="body">Request body for updating blacklist.</param>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::Nhentai.Api.Models.ErrorResponse">When receiving a 400 status code</exception>
        /// <exception cref="global::Nhentai.Api.Models.ErrorResponse">When receiving a 401 status code</exception>
        /// <exception cref="global::Nhentai.Api.Models.HTTPValidationError">When receiving a 422 status code</exception>
        /// <exception cref="global::Nhentai.Api.Models.ErrorResponse">When receiving a 429 status code</exception>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::Nhentai.Api.Models.BlacklistResponse?> PostAsync(global::Nhentai.Api.Models.BlacklistUpdateRequest body, Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::Nhentai.Api.Models.BlacklistResponse> PostAsync(global::Nhentai.Api.Models.BlacklistUpdateRequest body, Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = ToPostRequestInformation(body, requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "400", global::Nhentai.Api.Models.ErrorResponse.CreateFromDiscriminatorValue },
                { "401", global::Nhentai.Api.Models.ErrorResponse.CreateFromDiscriminatorValue },
                { "422", global::Nhentai.Api.Models.HTTPValidationError.CreateFromDiscriminatorValue },
                { "429", global::Nhentai.Api.Models.ErrorResponse.CreateFromDiscriminatorValue },
            };
            return await RequestAdapter.SendAsync<global::Nhentai.Api.Models.BlacklistResponse>(requestInfo, global::Nhentai.Api.Models.BlacklistResponse.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Get the authenticated user&apos;s blacklisted tags.---**Auth:** User Token or API Key**Rate limits:**- 15/1min per user- 15/1min per API key owner
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.GET, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            return requestInfo;
        }
        /// <summary>
        /// Add or remove tags from the authenticated user&apos;s blacklist.---**Auth:** User Token or API Key**Rate limits:**- 20/15min per user- 20/15min per API key owner
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="body">Request body for updating blacklist.</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToPostRequestInformation(global::Nhentai.Api.Models.BlacklistUpdateRequest body, Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToPostRequestInformation(global::Nhentai.Api.Models.BlacklistUpdateRequest body, Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = new RequestInformation(Method.POST, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            requestInfo.SetContentFromParsable(RequestAdapter, "application/json", body);
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::Nhentai.Api.Api.V2.Blacklist.BlacklistRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::Nhentai.Api.Api.V2.Blacklist.BlacklistRequestBuilder WithUrl(string rawUrl)
        {
            return new global::Nhentai.Api.Api.V2.Blacklist.BlacklistRequestBuilder(rawUrl, RequestAdapter);
        }
        /// <summary>
        /// Configuration for the request such as headers, query parameters, and middleware options.
        /// </summary>
        [Obsolete("This class is deprecated. Please use the generic RequestConfiguration class generated by the generator.")]
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class BlacklistRequestBuilderGetRequestConfiguration : RequestConfiguration<DefaultQueryParameters>
        {
        }
        /// <summary>
        /// Configuration for the request such as headers, query parameters, and middleware options.
        /// </summary>
        [Obsolete("This class is deprecated. Please use the generic RequestConfiguration class generated by the generator.")]
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class BlacklistRequestBuilderPostRequestConfiguration : RequestConfiguration<DefaultQueryParameters>
        {
        }
    }
}
#pragma warning restore CS0618
