// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using Nh.Api.Api.V2.User.Avatar;
using Nh.Api.Api.V2.User.Keys;
using Nh.Api.Models;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace Nh.Api.Api.V2.User
{
    /// <summary>
    /// Builds and executes requests for operations under \api\v2\user
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class UserRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The avatar property</summary>
        public global::Nh.Api.Api.V2.User.Avatar.AvatarRequestBuilder Avatar
        {
            get => new global::Nh.Api.Api.V2.User.Avatar.AvatarRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The keys property</summary>
        public global::Nh.Api.Api.V2.User.Keys.KeysRequestBuilder Keys
        {
            get => new global::Nh.Api.Api.V2.User.Keys.KeysRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Nh.Api.Api.V2.User.UserRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public UserRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/v2/user", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Nh.Api.Api.V2.User.UserRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public UserRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/v2/user", rawUrl)
        {
        }
        /// <summary>
        /// Delete your account. Requires password and username confirmation.---**Auth:** User Token required**Rate limits:**- 3/1h per user- 3/1h per IP + user
        /// </summary>
        /// <returns>A <see cref="global::Nh.Api.Models.DeleteProfileResponse"/></returns>
        /// <param name="body">Request body for deleting user profile.</param>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::Nh.Api.Models.ErrorResponse">When receiving a 400 status code</exception>
        /// <exception cref="global::Nh.Api.Models.ErrorResponse">When receiving a 401 status code</exception>
        /// <exception cref="global::Nh.Api.Models.HTTPValidationError">When receiving a 422 status code</exception>
        /// <exception cref="global::Nh.Api.Models.ErrorResponse">When receiving a 429 status code</exception>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::Nh.Api.Models.DeleteProfileResponse?> DeleteAsync(global::Nh.Api.Models.DeleteProfileRequest body, Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::Nhentai.Api.Models.DeleteProfileResponse> DeleteAsync(global::Nhentai.Api.Models.DeleteProfileRequest body, Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = ToDeleteRequestInformation(body, requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "400", global::Nh.Api.Models.ErrorResponse.CreateFromDiscriminatorValue },
                { "401", global::Nh.Api.Models.ErrorResponse.CreateFromDiscriminatorValue },
                { "422", global::Nh.Api.Models.HTTPValidationError.CreateFromDiscriminatorValue },
                { "429", global::Nh.Api.Models.ErrorResponse.CreateFromDiscriminatorValue },
            };
            return await RequestAdapter.SendAsync<global::Nh.Api.Models.DeleteProfileResponse>(requestInfo, global::Nh.Api.Models.DeleteProfileResponse.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Get your profile info. Email is hidden for API key auth.---**Auth:** User Token or API Key**Rate limits:**- 30/1min per user- 30/1min per API key owner
        /// </summary>
        /// <returns>A <see cref="global::Nh.Api.Models.UserMeResponse"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::Nh.Api.Models.ErrorResponse">When receiving a 401 status code</exception>
        /// <exception cref="global::Nh.Api.Models.ErrorResponse">When receiving a 429 status code</exception>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::Nh.Api.Models.UserMeResponse?> GetAsync(Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::Nhentai.Api.Models.UserMeResponse> GetAsync(Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToGetRequestInformation(requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "401", global::Nh.Api.Models.ErrorResponse.CreateFromDiscriminatorValue },
                { "429", global::Nh.Api.Models.ErrorResponse.CreateFromDiscriminatorValue },
            };
            return await RequestAdapter.SendAsync<global::Nh.Api.Models.UserMeResponse>(requestInfo, global::Nh.Api.Models.UserMeResponse.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Update your profile.---**Auth:** User Token required**Rate limits:**- 30/15min per user- 30/15min per IP + user
        /// </summary>
        /// <returns>A <see cref="global::Nh.Api.Models.UpdateProfileResponse"/></returns>
        /// <param name="body">Request body for updating user profile.</param>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::Nh.Api.Models.ErrorResponse">When receiving a 400 status code</exception>
        /// <exception cref="global::Nh.Api.Models.ErrorResponse">When receiving a 401 status code</exception>
        /// <exception cref="global::Nh.Api.Models.ErrorResponse">When receiving a 409 status code</exception>
        /// <exception cref="global::Nh.Api.Models.HTTPValidationError">When receiving a 422 status code</exception>
        /// <exception cref="global::Nh.Api.Models.ErrorResponse">When receiving a 429 status code</exception>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::Nh.Api.Models.UpdateProfileResponse?> PutAsync(global::Nh.Api.Models.UpdateProfileRequest body, Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::Nhentai.Api.Models.UpdateProfileResponse> PutAsync(global::Nhentai.Api.Models.UpdateProfileRequest body, Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = ToPutRequestInformation(body, requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "400", global::Nh.Api.Models.ErrorResponse.CreateFromDiscriminatorValue },
                { "401", global::Nh.Api.Models.ErrorResponse.CreateFromDiscriminatorValue },
                { "409", global::Nh.Api.Models.ErrorResponse.CreateFromDiscriminatorValue },
                { "422", global::Nh.Api.Models.HTTPValidationError.CreateFromDiscriminatorValue },
                { "429", global::Nh.Api.Models.ErrorResponse.CreateFromDiscriminatorValue },
            };
            return await RequestAdapter.SendAsync<global::Nh.Api.Models.UpdateProfileResponse>(requestInfo, global::Nh.Api.Models.UpdateProfileResponse.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Delete your account. Requires password and username confirmation.---**Auth:** User Token required**Rate limits:**- 3/1h per user- 3/1h per IP + user
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="body">Request body for deleting user profile.</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToDeleteRequestInformation(global::Nh.Api.Models.DeleteProfileRequest body, Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToDeleteRequestInformation(global::Nhentai.Api.Models.DeleteProfileRequest body, Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = new RequestInformation(Method.DELETE, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            requestInfo.SetContentFromParsable(RequestAdapter, "application/json", body);
            return requestInfo;
        }
        /// <summary>
        /// Get your profile info. Email is hidden for API key auth.---**Auth:** User Token or API Key**Rate limits:**- 30/1min per user- 30/1min per API key owner
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.GET, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            return requestInfo;
        }
        /// <summary>
        /// Update your profile.---**Auth:** User Token required**Rate limits:**- 30/15min per user- 30/15min per IP + user
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="body">Request body for updating user profile.</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToPutRequestInformation(global::Nh.Api.Models.UpdateProfileRequest body, Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToPutRequestInformation(global::Nhentai.Api.Models.UpdateProfileRequest body, Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = new RequestInformation(Method.PUT, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            requestInfo.SetContentFromParsable(RequestAdapter, "application/json", body);
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::Nh.Api.Api.V2.User.UserRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::Nh.Api.Api.V2.User.UserRequestBuilder WithUrl(string rawUrl)
        {
            return new global::Nh.Api.Api.V2.User.UserRequestBuilder(rawUrl, RequestAdapter);
        }
        /// <summary>
        /// Configuration for the request such as headers, query parameters, and middleware options.
        /// </summary>
        [Obsolete("This class is deprecated. Please use the generic RequestConfiguration class generated by the generator.")]
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class UserRequestBuilderDeleteRequestConfiguration : RequestConfiguration<DefaultQueryParameters>
        {
        }
        /// <summary>
        /// Configuration for the request such as headers, query parameters, and middleware options.
        /// </summary>
        [Obsolete("This class is deprecated. Please use the generic RequestConfiguration class generated by the generator.")]
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class UserRequestBuilderGetRequestConfiguration : RequestConfiguration<DefaultQueryParameters>
        {
        }
        /// <summary>
        /// Configuration for the request such as headers, query parameters, and middleware options.
        /// </summary>
        [Obsolete("This class is deprecated. Please use the generic RequestConfiguration class generated by the generator.")]
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class UserRequestBuilderPutRequestConfiguration : RequestConfiguration<DefaultQueryParameters>
        {
        }
    }
}
#pragma warning restore CS0618
