// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using Nh.Api.Api.V2.Galleries.Item.Comments;
using Nh.Api.Api.V2.Galleries.Item.Edit;
using Nh.Api.Api.V2.Galleries.Item.Favorite;
using Nh.Api.Api.V2.Galleries.Item.Related;
using Nh.Api.Models;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace Nh.Api.Api.V2.Galleries.Item
{
    /// <summary>
    /// Builds and executes requests for operations under \api\v2\galleries\{gallery_id}
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class WithGallery_ItemRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The comments property</summary>
        public global::Nh.Api.Api.V2.Galleries.Item.Comments.CommentsRequestBuilder Comments
        {
            get => new global::Nh.Api.Api.V2.Galleries.Item.Comments.CommentsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The edit property</summary>
        public global::Nh.Api.Api.V2.Galleries.Item.Edit.EditRequestBuilder Edit
        {
            get => new global::Nh.Api.Api.V2.Galleries.Item.Edit.EditRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The favorite property</summary>
        public global::Nh.Api.Api.V2.Galleries.Item.Favorite.FavoriteRequestBuilder Favorite
        {
            get => new global::Nh.Api.Api.V2.Galleries.Item.Favorite.FavoriteRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The related property</summary>
        public global::Nh.Api.Api.V2.Galleries.Item.Related.RelatedRequestBuilder Related
        {
            get => new global::Nh.Api.Api.V2.Galleries.Item.Related.RelatedRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Nh.Api.Api.V2.Galleries.Item.WithGallery_ItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WithGallery_ItemRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/v2/galleries/{gallery_id}{?include*}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Nh.Api.Api.V2.Galleries.Item.WithGallery_ItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WithGallery_ItemRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/v2/galleries/{gallery_id}{?include*}", rawUrl)
        {
        }
        /// <summary>
        /// Get a single gallery with full details and optional includes.---**Auth:** Public (optional User Token or API Key for personalization)**Rate limits:**- 45/1min per IP
        /// </summary>
        /// <returns>A <see cref="global::Nh.Api.Models.GalleryDetailResponse"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::Nh.Api.Models.ErrorResponse">When receiving a 404 status code</exception>
        /// <exception cref="global::Nh.Api.Models.HTTPValidationError">When receiving a 422 status code</exception>
        /// <exception cref="global::Nh.Api.Models.ErrorResponse">When receiving a 429 status code</exception>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::Nh.Api.Models.GalleryDetailResponse?> GetAsync(Action<RequestConfiguration<global::Nh.Api.Api.V2.Galleries.Item.WithGallery_ItemRequestBuilder.WithGallery_ItemRequestBuilderGetQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::Nhentai.Api.Models.GalleryDetailResponse> GetAsync(Action<RequestConfiguration<global::Nhentai.Api.Api.V2.Galleries.Item.WithGallery_ItemRequestBuilder.WithGallery_ItemRequestBuilderGetQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToGetRequestInformation(requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "404", global::Nh.Api.Models.ErrorResponse.CreateFromDiscriminatorValue },
                { "422", global::Nh.Api.Models.HTTPValidationError.CreateFromDiscriminatorValue },
                { "429", global::Nh.Api.Models.ErrorResponse.CreateFromDiscriminatorValue },
            };
            return await RequestAdapter.SendAsync<global::Nh.Api.Models.GalleryDetailResponse>(requestInfo, global::Nh.Api.Models.GalleryDetailResponse.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Get a single gallery with full details and optional includes.---**Auth:** Public (optional User Token or API Key for personalization)**Rate limits:**- 45/1min per IP
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::Nh.Api.Api.V2.Galleries.Item.WithGallery_ItemRequestBuilder.WithGallery_ItemRequestBuilderGetQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::Nhentai.Api.Api.V2.Galleries.Item.WithGallery_ItemRequestBuilder.WithGallery_ItemRequestBuilderGetQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.GET, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::Nh.Api.Api.V2.Galleries.Item.WithGallery_ItemRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::Nh.Api.Api.V2.Galleries.Item.WithGallery_ItemRequestBuilder WithUrl(string rawUrl)
        {
            return new global::Nh.Api.Api.V2.Galleries.Item.WithGallery_ItemRequestBuilder(rawUrl, RequestAdapter);
        }
        /// <summary>
        /// Get a single gallery with full details and optional includes.---**Auth:** Public (optional User Token or API Key for personalization)**Rate limits:**- 45/1min per IP
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class WithGallery_ItemRequestBuilderGetQueryParameters 
        {
            /// <summary>Comma-separated: comments,related,favorite</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("include")]
            public string? Include { get; set; }
#nullable restore
#else
            [QueryParameter("include")]
            public string Include { get; set; }
#endif
        }
        /// <summary>
        /// Configuration for the request such as headers, query parameters, and middleware options.
        /// </summary>
        [Obsolete("This class is deprecated. Please use the generic RequestConfiguration class generated by the generator.")]
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class WithGallery_ItemRequestBuilderGetRequestConfiguration : RequestConfiguration<global::Nh.Api.Api.V2.Galleries.Item.WithGallery_ItemRequestBuilder.WithGallery_ItemRequestBuilderGetQueryParameters>
        {
        }
    }
}
#pragma warning restore CS0618
