// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Nhentai.Api.Api.V2.Tags.Item
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum GetSortQueryParameterType
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "name")]
        #pragma warning disable CS1591
        Name,
        #pragma warning restore CS1591
        [EnumMember(Value = "popular")]
        #pragma warning disable CS1591
        Popular,
        #pragma warning restore CS1591
    }
}
