// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using Nh.Api.Api.V2.Auth;
using Nh.Api.Api.V2.Blacklist;
using Nh.Api.Api.V2.Captcha;
using Nh.Api.Api.V2.Cdn;
using Nh.Api.Api.V2.Comments;
using Nh.Api.Api.V2.Config;
using Nh.Api.Api.V2.Favorites;
using Nh.Api.Api.V2.Galleries;
using Nh.Api.Api.V2.Moderation;
using Nh.Api.Api.V2.Pow;
using Nh.Api.Api.V2.Search;
using Nh.Api.Api.V2.Tags;
using Nh.Api.Api.V2.User;
using Nh.Api.Api.V2.Users;
using Nh.Api.Api.V2.Zones;
using Nh.Api.Models;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace Nh.Api.Api.V2
{
    /// <summary>
    /// Builds and executes requests for operations under \api\v2
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class V2RequestBuilder : BaseRequestBuilder
    {
        /// <summary>The auth property</summary>
        public global::Nh.Api.Api.V2.Auth.AuthRequestBuilder Auth
        {
            get => new global::Nh.Api.Api.V2.Auth.AuthRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The blacklist property</summary>
        public global::Nh.Api.Api.V2.Blacklist.BlacklistRequestBuilder Blacklist
        {
            get => new global::Nh.Api.Api.V2.Blacklist.BlacklistRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The captcha property</summary>
        public global::Nh.Api.Api.V2.Captcha.CaptchaRequestBuilder Captcha
        {
            get => new global::Nh.Api.Api.V2.Captcha.CaptchaRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The cdn property</summary>
        public global::Nh.Api.Api.V2.Cdn.CdnRequestBuilder Cdn
        {
            get => new global::Nh.Api.Api.V2.Cdn.CdnRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The comments property</summary>
        public global::Nh.Api.Api.V2.Comments.CommentsRequestBuilder Comments
        {
            get => new global::Nh.Api.Api.V2.Comments.CommentsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The config property</summary>
        public global::Nh.Api.Api.V2.Config.ConfigRequestBuilder Config
        {
            get => new global::Nh.Api.Api.V2.Config.ConfigRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The favorites property</summary>
        public global::Nh.Api.Api.V2.Favorites.FavoritesRequestBuilder Favorites
        {
            get => new global::Nh.Api.Api.V2.Favorites.FavoritesRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The galleries property</summary>
        public global::Nh.Api.Api.V2.Galleries.GalleriesRequestBuilder Galleries
        {
            get => new global::Nh.Api.Api.V2.Galleries.GalleriesRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The moderation property</summary>
        public global::Nh.Api.Api.V2.Moderation.ModerationRequestBuilder Moderation
        {
            get => new global::Nh.Api.Api.V2.Moderation.ModerationRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The pow property</summary>
        public global::Nh.Api.Api.V2.Pow.PowRequestBuilder Pow
        {
            get => new global::Nh.Api.Api.V2.Pow.PowRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The search property</summary>
        public global::Nh.Api.Api.V2.Search.SearchRequestBuilder Search
        {
            get => new global::Nh.Api.Api.V2.Search.SearchRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The tags property</summary>
        public global::Nh.Api.Api.V2.Tags.TagsRequestBuilder Tags
        {
            get => new global::Nh.Api.Api.V2.Tags.TagsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The user property</summary>
        public global::Nh.Api.Api.V2.User.UserRequestBuilder User
        {
            get => new global::Nh.Api.Api.V2.User.UserRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The users property</summary>
        public global::Nh.Api.Api.V2.Users.UsersRequestBuilder Users
        {
            get => new global::Nh.Api.Api.V2.Users.UsersRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The zones property</summary>
        public global::Nh.Api.Api.V2.Zones.ZonesRequestBuilder Zones
        {
            get => new global::Nh.Api.Api.V2.Zones.ZonesRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Nh.Api.Api.V2.V2RequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public V2RequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/v2", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Nh.Api.Api.V2.V2RequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public V2RequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/v2", rawUrl)
        {
        }
        /// <summary>
        /// API root.---**Auth:** Public (no authentication required)
        /// </summary>
        /// <returns>A <see cref="global::Nh.Api.Models.ApiRootResponse"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::Nh.Api.Models.ApiRootResponse?> GetAsync(Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::Nhentai.Api.Models.ApiRootResponse> GetAsync(Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToGetRequestInformation(requestConfiguration);
            return await RequestAdapter.SendAsync<global::Nh.Api.Models.ApiRootResponse>(requestInfo, global::Nh.Api.Models.ApiRootResponse.CreateFromDiscriminatorValue, default, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// API root.---**Auth:** Public (no authentication required)
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.GET, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::Nh.Api.Api.V2.V2RequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::Nh.Api.Api.V2.V2RequestBuilder WithUrl(string rawUrl)
        {
            return new global::Nh.Api.Api.V2.V2RequestBuilder(rawUrl, RequestAdapter);
        }
        /// <summary>
        /// Configuration for the request such as headers, query parameters, and middleware options.
        /// </summary>
        [Obsolete("This class is deprecated. Please use the generic RequestConfiguration class generated by the generator.")]
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class V2RequestBuilderGetRequestConfiguration : RequestConfiguration<DefaultQueryParameters>
        {
        }
    }
}
#pragma warning restore CS0618
