// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using Nh.Api.Api.V2.Tags.Ids;
using Nh.Api.Api.V2.Tags.Item;
using Nh.Api.Api.V2.Tags.Search;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace Nh.Api.Api.V2.Tags
{
    /// <summary>
    /// Builds and executes requests for operations under \api\v2\tags
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class TagsRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The ids property</summary>
        public global::Nh.Api.Api.V2.Tags.Ids.IdsRequestBuilder Ids
        {
            get => new global::Nh.Api.Api.V2.Tags.Ids.IdsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The search property</summary>
        public global::Nh.Api.Api.V2.Tags.Search.SearchRequestBuilder Search
        {
            get => new global::Nh.Api.Api.V2.Tags.Search.SearchRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>Gets an item from the Nhentai.Api.api.v2.tags.item collection</summary>
        /// <param name="position">Unique identifier of the item</param>
        /// <returns>A <see cref="global::Nh.Api.Api.V2.Tags.Item.WithTag_typeItemRequestBuilder"/></returns>
        public global::Nh.Api.Api.V2.Tags.Item.WithTag_typeItemRequestBuilder this[string position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                urlTplParams.Add("tag_type", position);
                return new global::Nh.Api.Api.V2.Tags.Item.WithTag_typeItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Nh.Api.Api.V2.Tags.TagsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public TagsRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/v2/tags", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Nh.Api.Api.V2.Tags.TagsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public TagsRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/v2/tags", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
