// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using Nh.Api.Api.V2.Comments.Flags.Item.Review;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace Nh.Api.Api.V2.Comments.Flags.Item
{
    /// <summary>
    /// Builds and executes requests for operations under \api\v2\comments\flags\{flag_id}
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class WithFlag_ItemRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The review property</summary>
        public global::Nh.Api.Api.V2.Comments.Flags.Item.Review.ReviewRequestBuilder Review
        {
            get => new global::Nh.Api.Api.V2.Comments.Flags.Item.Review.ReviewRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Nh.Api.Api.V2.Comments.Flags.Item.WithFlag_ItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WithFlag_ItemRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/v2/comments/flags/{flag_id}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Nh.Api.Api.V2.Comments.Flags.Item.WithFlag_ItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WithFlag_ItemRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/v2/comments/flags/{flag_id}", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
